from playwright.sync_api import sync_playwright
import json
from pathlib import Path
import os
OUTPUT=Path(os.environ.get("NADI_TEST_ARTIFACT_DIR", "/tmp/nadi-bundle-c-browser"))
OUTPUT.mkdir(parents=True, exist_ok=True)
checks=[]
def check(label,value):
    assert value,label
    checks.append(label)
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True)
    context=browser.new_context(viewport={'width':1365,'height':1000})
    blocked=[]
    def allow(route):
        if route.request.url.startswith(('http://127.0.0.1:13033/','http://127.0.0.1:13034/')):route.continue_()
        else:blocked.append(route.request.url.split(':')[0]);route.abort()
    context.route('**/*',allow)
    page=context.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto('http://127.0.0.1:13033/engineering/workflow')
    page.get_by_role('heading',name='Asset Health 360',exact=True).wait_for()
    check('clear synthetic disclosure','DEMO • NOT OPERATIONAL' in page.locator('main').inner_text())
    check('neutral health','NOT ASSESSED' in page.locator('main').inner_text())
    page.get_by_role('button',name='PdM Center',exact=True).click()
    page.get_by_label('Reported quantity',exact=True).fill('velocity')
    page.get_by_label('Value type',exact=True).select_option('NUMERIC')
    page.get_by_role('button',name='Save demo inspection draft',exact=True).click()
    check('blank numeric rejected','finite numeric' in page.locator('main').get_by_role('alert').inner_text())
    page.get_by_label('Original measurement',exact=True).fill('0')
    page.get_by_label('Original unit',exact=True).fill('mm/s')
    page.get_by_label('Inspector observations (one per line)',exact=True).fill('Synthetic reported observation')
    page.get_by_label('HUMAN HYPOTHESIS (one per line)',exact=True).fill('Synthetic human hypothesis')
    page.get_by_role('button',name='Save demo inspection draft',exact=True).click()
    check('zero and units preserved','Reported measurement: 0 mm/s' in page.locator('main').inner_text())
    page.get_by_role('button',name='Submit inspection',exact=True).click()
    check('submitted not autoapproved','SUBMITTED' in page.locator('main').inner_text())
    page.get_by_role('button',name='Simulate independent review start',exact=True).click()
    page.get_by_role('button',name='Simulate approved',exact=True).click()
    check('review reason required','reviewer reason' in page.locator('main').get_by_role('alert').inner_text())
    page.get_by_label('Independent reviewer reason',exact=True).fill('Synthetic independent record review; no health claim')
    page.get_by_role('button',name='Simulate approved',exact=True).click()
    check('approved read only','Read-only approved revision' in page.locator('main').inner_text())
    page.get_by_role('button',name='Engineering Cases',exact=True).click()
    check('case screen selected',page.get_by_role('heading',name='Engineering Cases',exact=True).count()==1)
    page.get_by_label('Investigation hypotheses (one per line)',exact=True).fill('Synthetic human investigation hypothesis')
    page.get_by_role('button',name='Create demo Engineering Case',exact=True).click()
    page.get_by_role('button',name='Submit case',exact=True).click()
    page.get_by_role('button',name='Simulate case approved',exact=True).click()
    check('reviewed human lineage','Frozen inspection: inspection:demo-1 r4' in page.locator('main').inner_text())
    page.get_by_role('button',name='Recommendations',exact=True).click()
    page.get_by_label('Proposed action',exact=True).fill('Synthetic bounded follow-up proposal')
    page.get_by_label('Target date',exact=True).fill('2026-10-08')
    page.get_by_label('Link existing synthetic WO (informational)',exact=True).check()
    page.get_by_role('button',name='Save demo recommendation',exact=True).click()
    page.get_by_role('button',name='Submit recommendation',exact=True).click()
    page.get_by_role('button',name='Action Board',exact=True).click()
    check('awaiting review board','recommendation:demo-1' in page.locator('main').inner_text())
    page.get_by_role('button',name='Recommendations',exact=True).click()
    page.get_by_role('button',name='Simulate recommendation approved',exact=True).click()
    for label in ('Record local planned','Record local in progress','Record local completed'):
        page.get_by_role('button',name=label,exact=True).click()
    check('completed not autoverified','follow-up COMPLETED' in page.locator('main').inner_text())
    page.get_by_role('button',name='Simulate independent completion verification',exact=True).click()
    check('local verified not source closure','follow-up VERIFIED' in page.locator('main').inner_text() and 'no source mutation' in page.locator('main').inner_text())
    page.get_by_label('Search',exact=True).fill('not present')
    check('search filters scoped proposal',page.get_by_role('heading',name='recommendation:demo-1',exact=True).count()==0)
    page.get_by_label('Search',exact=True).fill('')
    page.get_by_role('button',name='PdM Center',exact=True).click()
    page.get_by_label('Reported quantity',exact=True).fill('Unsaved correction')
    page.on('dialog',lambda d:d.dismiss())
    page.get_by_role('button',name='Action Board',exact=True).click()
    check('unsaved navigation cancellation preserves editor',page.get_by_role('heading',name='PdM Center',exact=True).count()==1)
    # Reset only the browser presentation, no backend or source operation.
    page.close();page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto('http://127.0.0.1:13033/engineering/workflow');page.get_by_role('heading',name='Asset Health 360',exact=True).wait_for()
    page.get_by_label('Canonical asset',exact=True).select_option('asset:SYNTHETIC:B')
    check('unmapped not healthy','UNMAPPED / NO APPROVED SIGNALS' in page.locator('main').inner_text())
    for width in (390,768,1365):
        page.set_viewport_size({'width':width,'height':1000})
        for screen in ('PdM Center','Asset Health 360','Engineering Cases','Recommendations','Action Board'):
            page.get_by_role('button',name=screen,exact=True).click()
            check(f'no horizontal overflow {screen} {width}',page.evaluate('document.documentElement.scrollWidth<=window.innerWidth'))
        page.screenshot(path=str(OUTPUT / f'workflow-{width}.png'),full_page=True)
    check('no browser exceptions',not errors)
    check('no external requests',not blocked)
    browser.close()
(OUTPUT / 'workflow-results.json').write_text(json.dumps({'passed':len(checks),'checks':checks},indent=2))
print(f'Browser acceptance: {len(checks)} PASS')
