// Existing HTTPS frontend only. New synthetic case/rec rows; advisory UI fixtures are explicit.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.NADI_PLAYWRIGHT_MODULE).href);
const base='https://localhost:3000',out=resolve(process.env.NADI_BROWSER_OUTPUT??'/tmp/nadi-eng-browser');mkdirSync(out,{recursive:true});
const accounts=JSON.parse(readFileSync(process.env.NADI_QA_ACCOUNT_FILE,'utf8'));
const browser=await chromium.launch({headless:true}),checks=[],errors=[];
function check(name,ok){assert.ok(ok,name);checks.push(name);console.log('PASS '+name);}
async function login(context,who){const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/login',{waitUntil:'networkidle'});await p.getByLabel('Username',{exact:true}).fill(accounts[who].username);await p.getByLabel('Password',{exact:true}).fill(accounts[who].password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.waitForURL(base+'/engineering/local');return p;}
const a=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1086}}),r=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1086}});
try{
 const status=await(await a.request.get(base+'/api/development/status')).json();check('exact clean frontend/backend SHA',!status.dirty&&!status.stale&&status.sha===status.backend_sha&&status.sha===status.launched_sha);check('existing backends and fixture',status.backend==='AVAILABLE'&&status.factual_backend==='AVAILABLE'&&status.database_identity==='nadi_live_dev_test');
 const p=await login(a,'engineer'),reviewer=await login(r,'reviewer');check('Secure HttpOnly Strict QA cookie',(await a.cookies()).some(c=>c.secure&&c.httpOnly&&c.sameSite==='Strict'));
 await p.goto(base+'/engineering/cases',{waitUntil:'networkidle'});await p.getByRole('button',{name:'New case',exact:true}).click();const title='SYNTHETIC QA ENG acceptance '+Date.now();
 await p.getByLabel('Case title',{exact:true}).fill(title);await p.getByLabel('Problem statement',{exact:true}).fill('Synthetic inspection context; no plant diagnosis or work instruction.');await p.locator('#case-observations').fill('Recorded observation from synthetic QA evidence.');await p.locator('#case-hypotheses').fill('Human hypothesis; NOT a diagnosis.');
 let attempts=[];let fail=true;
 await a.route('**/api/engineering-qa/cases',async route=>{if(route.request().method()!=='POST')return route.continue();attempts.push(route.request().postDataJSON().request_id);if(fail){fail=false;return route.fulfill({status:503,json:{detail:{code:'SYNTHETIC_RETRY_FAILURE'}}});}return route.continue();});
 await p.getByRole('button',{name:'Save case',exact:true}).click();await p.getByRole('alert').filter({hasText:'SYNTHETIC_RETRY_FAILURE'}).waitFor();check('failed save retains structured input',await p.getByLabel('Case title',{exact:true}).inputValue()===title);
 await p.getByRole('button',{name:'Save case',exact:true}).click();await p.waitForURL(/record=case/);await p.getByRole('heading',{name:title,exact:true}).waitFor();check('retry retains exact idempotency ID',attempts.length===2&&attempts[0]===attempts[1]);await a.unroute('**/api/engineering-qa/cases');
 const id=new URL(p.url()).searchParams.get('record'),who=await(await a.request.get(base+'/api/engineering-qa/session')).json();
 let row=await(await a.request.get(base+'/api/engineering-qa/cases/'+encodeURIComponent(id))).json();
 await p.getByRole('button',{name:'Edit case',exact:true}).click();await p.getByLabel('Case title',{exact:true}).fill(title+' revised');
 const note=await a.request.post(base+'/api/engineering-qa/cases/'+encodeURIComponent(id)+'/notes',{headers:{Origin:base,'X-CSRF-Token':who.csrf_token},data:{request_id:crypto.randomUUID(),expected_revision:row.revision,text:'Synthetic concurrent note'}});check('controlled CAS conflict fixture accepted',note.status()===200);
 await p.getByRole('button',{name:'Save case',exact:true}).click();await p.getByRole('alert').filter({hasText:'REVISION_CONFLICT'}).waitFor();check('409 preserves unsaved edit',await p.getByLabel('Case title',{exact:true}).inputValue()===title+' revised');
 await p.getByRole('button',{name:'Read latest revision (keep unsaved form)',exact:true}).click();await p.getByText(new RegExp('Revision 2')).first().waitFor();check('explicit latest read preserves unsaved form',await p.getByLabel('Case title',{exact:true}).inputValue()===title+' revised');await p.getByRole('button',{name:'Save case',exact:true}).click();await p.getByRole('heading',{name:title+' revised',exact:true}).waitFor();
 await p.getByLabel('Exact evidence record reference',{exact:true}).fill(accounts.asset);await p.getByRole('button',{name:'Link frozen evidence',exact:true}).click();await p.getByRole('region',{name:'Case evidence provenance',exact:true}).waitFor();await p.getByRole('button',{name:'Submit case for review',exact:true}).click();await p.locator('.status-badge').filter({hasText:'IN_REVIEW'}).first().waitFor();
 row=await(await a.request.get(base+'/api/engineering-qa/cases/'+encodeURIComponent(id))).json();const self=await a.request.post(base+'/api/engineering-qa/cases/'+encodeURIComponent(id)+'/review',{headers:{Origin:base,'X-CSRF-Token':who.csrf_token},data:{request_id:crypto.randomUUID(),expected_revision:row.revision,decision:'APPROVED',reason:'Synthetic self review attempt'}});check('server rejects self review',self.status()===403);
 await reviewer.goto(base+'/engineering/cases?record='+encodeURIComponent(id),{waitUntil:'networkidle'});await reviewer.getByLabel('Review / revision rationale',{exact:true}).fill('Independent review of synthetic evidence only.');await reviewer.getByRole('button',{name:'Approve case',exact:true}).click();await reviewer.locator('.status-badge').filter({hasText:'APPROVED'}).first().waitFor();
 await p.goto(base+'/engineering/cases?record='+encodeURIComponent(id),{waitUntil:'networkidle'});await p.getByLabel('Recommendation rationale',{exact:true}).fill('Synthetic reviewed finding; human interpretation is limited.');await p.getByLabel('Proposed local follow-up',{exact:true}).fill('Propose a bounded QA follow-up; no maintenance authorization.');await p.getByRole('button',{name:'Create linked recommendation',exact:true}).click();await p.waitForURL(/\/recommendations\?record=/);const recId=new URL(p.url()).searchParams.get('record');await p.getByRole('button',{name:'Submit recommendation for review',exact:true}).click();await p.getByRole('button',{name:'Submit recommendation for review',exact:true}).waitFor({state:'hidden'});
 await reviewer.goto(base+'/recommendations?record='+encodeURIComponent(recId),{waitUntil:'networkidle'});await reviewer.getByLabel('Recommendation review / follow-up rationale',{exact:true}).fill('Independent synthetic proposal review.');await reviewer.getByRole('button',{name:'Approve recommendation',exact:true}).click();await reviewer.getByRole('button',{name:'Approve recommendation',exact:true}).waitFor({state:'hidden'});
 await p.goto(base+'/action-board?record='+encodeURIComponent(recId),{waitUntil:'networkidle'});await p.getByLabel('Recommendation review / follow-up rationale',{exact:true}).fill('Synthetic local plan; not physical work.');await p.getByRole('button',{name:'Record local PLANNED',exact:true}).click();await p.getByRole('button',{name:'Record local IN_PROGRESS',exact:true}).waitFor();check('existing Action Board structured follow-up works',true);
 await p.goto(base+'/engineering/advisories',{waitUntil:'networkidle'});await p.getByText('Advisory persistence BLOCKED — QA schema prerequisite',{exact:true}).waitFor();check('persistent advisory write gate is explicit',await p.getByRole('button',{name:'New advisory',exact:true}).count()===0);
 await p.goto(base+'/engineering/inbox',{waitUntil:'networkidle'});await p.getByText('Advisory persistence BLOCKED — QA schema prerequisite',{exact:true}).waitFor();check('no misleading persistent recipient records',await p.getByRole('button',{name:'Acknowledge receipt only',exact:true}).count()===0);
 for(const width of [1440,768,390]){
  await p.setViewportSize({width,height:1086});await p.goto(base+'/engineering/cases?record='+encodeURIComponent(id),{waitUntil:'networkidle'});await p.getByRole('heading',{name:title+' revised',exact:true}).waitFor();check('case no page overflow '+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('case one main '+width,await p.getByRole('main').count()===1);await p.screenshot({path:out+'/case-'+width+'.png',fullPage:true});
 }
 const mock=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1086}}),m=await mock.newPage();m.on('pageerror',e=>errors.push(e.message));let role='AUTHOR';const demo={record_id:'advisory:DEMO-ENG-01',canonical_asset_id:'asset:SYNTHETIC:UI',revision:1,status:'DRAFT',created_by:'demo-engineer',created_at:'2026-10-11T00:00:00Z',updated_at:'2026-10-11T00:00:00Z',review:null,summary:'DEMO / SYNTHETIC QA — reviewed finding',finding:'Observed a synthetic change. Interpretation requires controlled evidence; no equipment diagnosis.',evidence_caveat:'DEMO evidence only. Asset condition and actual plant action are UNKNOWN.',audiences:['OPERATIONS_QA','MAINTENANCE_QA'],replaces:null,recommendation_ref:'recommendation:DEMO',availability:'UNPUBLISHED',publication:null,scope:'SYNTHETIC_QA_ONLY_NOT_WORK_AUTHORIZATION',upstream:{case_id:'case:DEMO',case_revision:4,case_sha256:'a'.repeat(64),recommendation_id:'recommendation:DEMO',recommendation_revision:3,recommendation_sha256:'b'.repeat(64),case_reviewer:'demo-reviewer',recommendation_reviewer:'demo-reviewer',recommended_action:'Propose a bounded synthetic QA follow-up; not plant work authorization.',rationale:'Reviewed demo evidence with explicit limits.',responsible_person_ref:null,responsible_team_ref:null,target_date:null,existing_work_order_ref:null,evidence:[{kind:'ASSET',record_id:'asset:SYNTHETIC:UI',mode:'FROZEN_SNAPSHOT',stable_version:'DEMO-1',source_timestamp:null}]}};let ack=null;
 await mock.route('**/api/engineering-qa/**',async route=>{const path=new URL(route.request().url()).pathname.split('/api/engineering-qa/')[1],method=route.request().method();let body;if(path==='session')body={subject:role==='AUTHOR'?'demo-engineer':'demo-reviewer',roles:[role],asset_ids:[demo.canonical_asset_id],csrf_token:'DEMO_NOT_A_SESSION'};else if(path==='advisory-capability')body={scope:'SYNTHETIC_QA_ONLY',persistence:'READY'};else if(path==='advisories')body={items:[demo],total:1,offset:0,limit:25,has_more:false};else if(path.startsWith('advisories/')){if(method==='POST'){const action=path.split('/').at(-1);if(action==='submit'){demo.status='IN_REVIEW';demo.revision++;}if(action==='review'){demo.status='APPROVED';demo.review={reviewer:'demo-reviewer',decision:'APPROVED',rationale:'Reviewed DEMO only',decided_at:'2026-10-11T00:02:00Z'};demo.revision++;}if(action==='publish'){demo.revision++;demo.availability='IN_APP_QA_AVAILABLE';demo.publication={version:demo.revision,published_at:'2026-10-11T00:03:00Z',published_by:'demo-reviewer',snapshot:{...demo}};}if(action==='withdraw'){demo.availability='WITHDRAWN';demo.revision++;}}body=demo;}else if(path==='inbox')body={items:[{...demo.publication,current_revision:demo.revision,availability:demo.availability,acknowledgement:ack,follow_up_status:'PLANNED',viewed_status:'NOT_RECORDED'}],total:1,offset:0,limit:25,has_more:false};else if(path.startsWith('inbox/')){if(method==='POST')ack={actor:'demo-reviewer',updated_at:'2026-10-11T00:04:00Z',status:'ACKNOWLEDGED',meaning:'RECEIPT_ONLY_NOT_APPROVAL_OR_WORK_AUTHORIZATION'};body=method==='POST'?ack:{...demo.publication,current_revision:demo.revision,availability:demo.availability,acknowledgement:ack,follow_up_status:'PLANNED',viewed_status:'NOT_RECORDED'};}else return route.fulfill({status:404,json:{detail:{code:'DEMO_UNAVAILABLE'}}});return route.fulfill({json:body});});
 await m.goto(base+'/engineering/advisories?record='+demo.record_id,{waitUntil:'networkidle'});await m.getByRole('button',{name:'Submit advisory for review',exact:true}).click();await m.getByRole('button',{name:'Submit advisory for review',exact:true}).waitFor({state:'hidden'});role='REVIEWER';await m.reload({waitUntil:'networkidle'});await m.getByLabel('Advisory review / publication rationale',{exact:true}).fill('Independent DEMO review only');await m.getByRole('button',{name:'Approve advisory',exact:true}).click();await m.getByRole('button',{name:'Publish to QA inbox',exact:true}).waitFor();await m.getByLabel('Advisory review / publication rationale',{exact:true}).fill('Publish DEMO to simulated QA inbox');await m.getByRole('button',{name:'Publish to QA inbox',exact:true}).click();await m.getByRole('button',{name:'Withdraw advisory',exact:true}).waitFor();check('DEMO advisory UI review/publish interactions',true);
 for(const width of [1440,768,390]){await m.setViewportSize({width,height:1086});await m.goto(base+'/engineering/inbox?record='+demo.record_id,{waitUntil:'networkidle'});await m.getByRole('button',{name:'Acknowledge receipt only',exact:true}).waitFor();check('recipient no page overflow '+width,await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('complete source hash wraps '+width,await m.locator('.product-workspace p.identifier').evaluate(n=>getComputedStyle(n).whiteSpace==='normal'&&getComputedStyle(n).overflow==='visible'));check('unknown owner/date preserved '+width,(await m.getByRole('main').innerText()).includes('NOT ASSIGNED'));await m.screenshot({path:out+'/inbox-'+width+'.png',fullPage:true});}
 await m.getByRole('button',{name:'Acknowledge receipt only',exact:true}).click();await m.getByText(/^ACKNOWLEDGED ·/).waitFor();check('DEMO receipt disables duplicate click',await m.getByRole('button',{name:'Acknowledge receipt only',exact:true}).isDisabled());
 await m.goto(base+'/engineering/advisories?record='+demo.record_id,{waitUntil:'networkidle'});await m.getByLabel('Advisory review / publication rationale',{exact:true}).fill('Withdraw DEMO only');await m.getByRole('button',{name:'Withdraw advisory',exact:true}).click();await m.getByRole('button',{name:'Withdraw advisory',exact:true}).waitFor({state:'hidden'});await m.goto(base+'/engineering/inbox?record='+demo.record_id,{waitUntil:'networkidle'});await m.getByRole('button',{name:'Acknowledge receipt only',exact:true}).waitFor();check('DEMO withdrawn recipient cannot acknowledge',await m.getByRole('button',{name:'Acknowledge receipt only',exact:true}).isDisabled());check('no uncaught browser errors',errors.length===0);
 writeFileSync(out+'/report.json',JSON.stringify({status:'PASS',sha:status.sha,checks,actual_case_id:id,actual_recommendation_id:recId,advisory_runtime:'BLOCKED_SCHEMA_PREREQUISITE',advisory_screenshots:'SANITIZED DEMO UI FIXTURES — NOT DURABLE RUNTIME ACCEPTANCE'},null,2));await mock.close();
}finally{await a.close();await r.close();await browser.close();}
