// Actual assigned-account login and retained-record reads; simulated failures never contact the backend.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.NADI_PLAYWRIGHT_MODULE).href);
const base='https://localhost:3000',out=process.env.NADI_BROWSER_OUTPUT??'/tmp/nadi-c-browser';mkdirSync(out,{recursive:true});
const checks=[],screenshots=[],check=(n,v)=>{assert.ok(v,n);checks.push(n);console.log('PASS '+n);};
const browser=await chromium.launch({headless:true});
try{
 const actual=await browser.newContext({ignoreHTTPSErrors:true}),a=await actual.newPage();
 const status=await(await actual.request.get(base+'/api/development/status')).json();check('matching clean SHA and backends',!status.dirty&&!status.stale&&status.sha===status.backend_sha&&status.sha===status.launched_sha&&status.backend==='AVAILABLE'&&status.factual_backend==='AVAILABLE');
 for(const route of ['/','/assets','/asset-health','/maintenance','/work-orders','/data-quality'])check('anonymous factual access '+route,(await a.goto(base+route,{waitUntil:'networkidle'})).status()===200&&new URL(a.url()).pathname===route);
 const mock=await browser.newContext({ignoreHTTPSErrors:true}),p=await mock.newPage();let mode='invalid',posts=0,hold=false,release;const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await mock.route('**/api/development/status',r=>r.fulfill({json:{...status,database_identity:'DEMO_UI_FIXTURE'}}));
 await mock.route('**/api/engineering-qa/**',async r=>{check('existing credential POST only',r.request().url().endsWith('/auth/login')&&r.request().method()==='POST');check('credential payload unchanged',Object.keys(r.request().postDataJSON()).sort().join(',')===(mode==='policy'?'new_password,password,username':'password,username'));posts++;if(hold)await new Promise(done=>release=done);const codes={invalid:[401,'INVALID_CREDENTIALS'],limited:[429,'RATE_LIMITED'],unavailable:[503,'QA_BACKEND_UNAVAILABLE'],change:[401,'PASSWORD_CHANGE_REQUIRED'],policy:[422,'PASSWORD_POLICY_DENIED']};const [status,code]=codes[mode];await r.fulfill({status,json:{detail:{code}}});});
 const fill=async()=>{await p.getByLabel('Username',{exact:true}).fill('DEMO_TEST_ONLY');await p.getByLabel('Password',{exact:true}).fill('DEMO_NOT_CREDENTIAL');};
 const shot=async(name,width)=>{await p.evaluate(()=>{if(!document.querySelector('[data-login-evidence]')){const e=document.createElement('p');e.dataset.loginEvidence='true';e.textContent='DEMO · SYNTHETIC UI STATE; NOT AN ACCOUNT OR PLANT EVIDENCE';e.style.cssText='padding:12px;font-size:12px;border:1px solid #94a3b8;background:#fff;color:#102536';document.querySelector('.nadi-login-page').append(e);}});check('no overflow '+name+' '+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('single main '+name+' '+width,await p.getByRole('main').count()===1);const file=`login-${name}-${width}.png`;await p.screenshot({path:out+'/'+file,fullPage:true});screenshots.push(file);};
 for(const width of [1440,768,390]){
  await p.setViewportSize({width,height:1000});await p.goto(base+'/login',{waitUntil:'networkidle'});check('empty submit explained '+width,await p.getByRole('button',{name:'Sign in',exact:true}).isDisabled()&&await p.getByText('Username and password are required.',{exact:true}).isVisible());check('logo loaded '+width,await p.getByAltText('NADI — Platform Analitik Keandalan Aset Pembangkit').evaluate(n=>n.complete&&n.naturalWidth>0));check('44px controls '+width,await p.locator('.nadi-local-login input,.nadi-local-login button').evaluateAll(ns=>ns.every(n=>n.getBoundingClientRect().height>=44)));await shot('default',width);
  await p.getByLabel('Username',{exact:true}).focus();await p.keyboard.press('Tab');check('keyboard reaches password '+width,await p.getByLabel('Password',{exact:true}).evaluate(n=>n===document.activeElement));await fill();await p.getByRole('button',{name:'Show password',exact:true}).click();check('accessible reveal '+width,await p.getByLabel('Password',{exact:true}).getAttribute('type')==='text'&&await p.getByRole('button',{name:'Hide password',exact:true}).getAttribute('aria-pressed')==='true');await p.getByRole('button',{name:'Hide password',exact:true}).click();
  mode='invalid';hold=true;await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.getByRole('button',{name:'Signing in…',exact:true}).waitFor();check('busy prevents duplicate submit '+width,await p.getByRole('form',{name:'NADI sign-in'}).getAttribute('aria-busy')==='true'&&await p.locator('.nadi-local-login input,.nadi-local-login button').evaluateAll(ns=>ns.every(n=>n.disabled)));await shot('loading',width);hold=false;release();await p.getByRole('alert').waitFor();check('generic error receives focus '+width,await p.getByRole('alert').evaluate(n=>n===document.activeElement)&&(await p.getByRole('alert').innerText())==='Unable to sign in. Check your credentials.');check('password cleared '+width,await p.getByLabel('Password',{exact:true}).inputValue()==='');await shot('error',width);
  await p.goto(base+'/login?expired=1',{waitUntil:'networkidle'});check('expiry announced '+width,await p.getByRole('status').filter({hasText:'Your session expired or was revoked.'}).isVisible());await shot('expired',width);
 }
 for(const [next,message] of [['limited','Sign-in temporarily limited. Try later; no automatic retry.'],['unavailable','Sign-in is unavailable. Try later.']]){await p.goto(base+'/login',{waitUntil:'networkidle'});mode=next;await fill();const before=posts;await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.getByRole('alert').waitFor();check('bounded generic '+next,(await p.getByRole('alert').innerText())===message);await p.waitForTimeout(250);check('no retry '+next,posts===before+1);}
 await p.goto(base+'/login',{waitUntil:'networkidle'});mode='change';await fill();await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.getByLabel('New password',{exact:true}).waitFor();check('password change retains existing gate',await p.getByRole('button',{name:'Change password and sign in',exact:true}).isDisabled());mode='policy';await fill();await p.getByLabel('New password',{exact:true}).fill('DEMO_NEW_NOT_CREDENTIAL');await p.getByRole('button',{name:'Change password and sign in',exact:true}).click();await p.getByRole('alert').filter({hasText:'configured password policy'}).waitFor();check('policy failure clears passwords',await p.getByLabel('Password',{exact:true}).inputValue()===''&&await p.getByLabel('New password',{exact:true}).inputValue()==='');await shot('password-change',390);
 await p.setViewportSize({width:1440,height:1000});await p.goto(base+'/login',{waitUntil:'networkidle'});await p.getByRole('button',{name:'Switch to dark theme',exact:true}).click();check('dark theme preserved',await p.evaluate(()=>document.documentElement.dataset.theme==='dark'));await shot('dark',1440);check('no page errors',errors.length===0);await mock.close();
 if(process.env.NADI_QA_ACCOUNT_FILE){const accounts=JSON.parse(readFileSync(process.env.NADI_QA_ACCOUNT_FILE));await a.goto(base+'/login',{waitUntil:'networkidle'});await a.getByLabel('Username',{exact:true}).fill(accounts.engineer.username);await a.getByLabel('Password',{exact:true}).fill(accounts.engineer.password);await a.getByRole('button',{name:'Sign in',exact:true}).click();await a.waitForURL(base+'/engineering/local');check('assigned QA account works',await a.getByRole('heading',{name:'Trusted local session',exact:true}).isVisible());check('Secure HttpOnly Strict session',(await actual.cookies(base)).some(c=>c.secure&&c.httpOnly&&c.sameSite==='Strict'));if(process.env.NADI_PERSISTED_RECORD_FILE){const expected=JSON.parse(readFileSync(process.env.NADI_PERSISTED_RECORD_FILE));for(const [resource,row] of [['inspections',expected.inspection],['cases',expected.c],['recommendations',expected.recommendation]]){const r=await actual.request.get(base+'/api/engineering-qa/'+resource+'/'+(row.record_id??row.case_id));check('original '+resource+' retained',r.status()===200&&JSON.stringify(await r.json())===JSON.stringify(row));}}}
 await actual.close();writeFileSync(out+'/login-browser-report.json',JSON.stringify({status:'PASS',sha:status.sha,checks,screenshots,synthetic_screenshots:true},null,2));console.log('Login browser checks passed: '+checks.length);
}finally{await browser.close();}
