import assert from "node:assert/strict";
import {readFileSync,mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {execFileSync} from "node:child_process";
import {createRequire} from "node:module";
const output=mkdtempSync(join(tmpdir(),"nadi-phase2-contract-"));let count=0;
const test=(name,fn)=>{fn();count++;console.log(`PASS ${name}`);};
try{
 execFileSync(process.execPath,["node_modules/typescript/bin/tsc","lib/manual-pdm.ts","--outDir",output,"--target","ES2022","--module","commonjs","--skipLibCheck"],{stdio:"pipe"});
 const require=createRequire(import.meta.url);const {methods,validateInspection,enteredValue,localRecord,submitLocal}=require(join(output,"manual-pdm.js"));
 const input={canonical_asset_id:"asset:SYNTHETIC:A",method:"VIBRATION",method_version:"proposal-1",inspector_ref:"synthetic-inspector",inspected_at:null,quantity:"velocity",value:null,unit:"mm/s",operating_context:"",observations:[],interpretations:[]};
 test("six method extensions",()=>assert.equal(methods.length,6));
 test("unknown is null",()=>assert.equal(enteredValue("0","UNKNOWN"),null));
 test("numeric zero preserved",()=>assert.equal(enteredValue("0","NUMERIC"),0));
 test("blank numeric never zero",()=>assert.throws(()=>enteredValue(" ","NUMERIC")));
 test("text preserved",()=>assert.equal(enteredValue("trace","TEXT"),"trace"));
 test("boolean false preserved",()=>assert.equal(enteredValue("false","BOOLEAN"),false));
 test("invalid boolean rejected",()=>assert.throws(()=>enteredValue("0","BOOLEAN")));
 test("finite numbers only",()=>assert.throws(()=>enteredValue("Infinity","NUMERIC")));
 test("no inferred units",()=>{validateInspection({...input,unit:null});assert.equal(localRecord(input,"2026-10-09T12:00:00Z","synthetic").input.unit,"mm/s");});
 test("nonblank observations",()=>assert.throws(()=>validateInspection({...input,observations:[" "]})));
 test("at most20 interpretations",()=>assert.throws(()=>validateInspection({...input,interpretations:Array(21).fill("x")})));
 test("2000 Unicode codepoints allowed",()=>validateInspection({...input,interpretations:["🛠".repeat(2000)]}));
 test("explicit timezone required",()=>assert.throws(()=>validateInspection({...input,inspected_at:"2026-10-09T10:00:00"})));
 test("future inspection rejected",()=>assert.throws(()=>localRecord({...input,inspected_at:"2026-10-10T00:00:00Z"},"2026-10-09T00:00:00Z","synthetic")));
 const row=localRecord(input,"2026-10-09T12:00:00Z","synthetic");
 test("draft never health claim",()=>{assert.equal(row.assessment,"NOT_ASSESSED");assert.equal(row.status,"DRAFT");});
 test("submit requires revision",()=>assert.throws(()=>submitLocal(row,2,"2026-10-09T12:01:00Z"),/REVISION_CONFLICT/));
 test("submit not approve and history retained",()=>{const next=submitLocal(row,1,"2026-10-09T12:01:00Z");assert.equal(next.status,"IN_REVIEW");assert.equal(next.history.length,2);assert.equal(row.revision,1);});
 const view=readFileSync("components/Phase2Workspace.tsx","utf8"),route=readFileSync("app/engineering/lab/page.tsx","utf8");
 test("no operational requests",()=>assert.ok(!/fetch\(|axios|dangerouslySetInnerHTML/.test(view)));
 test("synthetic disclosure",()=>assert.ok(view.includes("SYNTHETIC LOCAL DEMO")&&view.includes("No authentication")));
 test("four shared contextual views",()=>{for(const label of ["PdM Center","Asset Health 360","Recommendations","Action Board"])assert.ok(view.includes(label));});
 test("development gating",()=>assert.ok(route.includes('if(mode!=="DEMO")')));
 test("unsaved protection",()=>assert.ok(view.includes('beforeunload')&&view.includes('dirty&&!window.confirm')));
 test("quality not health/freshness",()=>assert.ok(view.includes("Source quality does not prove freshness or equipment health")));
 test("reviewer not browser authority",()=>assert.ok(view.includes("No browser-controlled reviewer authority")));
 test("no WO mutation workflow",()=>assert.ok(view.includes("No Maximo WO create, update, approval or closure")));
 console.log(`Phase2 frontend checks passed: ${count}`);
}finally{rmSync(output,{recursive:true,force:true});}
