import assert from "node:assert/strict";
import {readFileSync,mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {execFileSync} from "node:child_process";
import {createRequire} from "node:module";
const output=mkdtempSync(join(tmpdir(),"nadi-workflow-"));let count=0;
const test=(name,fn)=>{fn();count++;console.log(`PASS ${name}`);};
try{
 execFileSync(process.execPath,["node_modules/typescript/bin/tsc","lib/engineering-workflow.ts","--outDir",output,"--target","ES2022","--module","commonjs","--skipLibCheck"],{stdio:"pipe"});
 const require=createRequire(import.meta.url),w=require(join(output,"engineering-workflow.js"));
 const now="2026-10-09T10:00:00Z",input={canonical_asset_id:"asset:SYNTHETIC:A",method:"VIBRATION",method_version:"proposal-1",inspector_ref:"demo-inspector",inspected_at:now,quantity:"velocity",value:null,unit:"mm/s",operating_context:"",observations:["Human observation"],interpretations:["Human hypothesis"]};
 let row=w.inspectionDraft(input,"inspection:synthetic",now);
 test("null and original unit retained",()=>{assert.equal(row.input.value,null);assert.equal(row.input.unit,"mm/s");});
 test("no unsafe attachment paths",()=>assert.throws(()=>w.inspectionDraft(input,"x",now,"../secret")));
 test("attachment never uploaded",()=>assert.equal(w.inspectionDraft(input,"x",now,"test.pdf").attachment.status,"METADATA_ONLY_NOT_UPLOADED"));
 test("timezone mandatory",()=>assert.throws(()=>w.inspectionDraft({...input,inspected_at:"2026-10-09T10:00:00"},"x",now)));
 test("revision conflict",()=>assert.throws(()=>w.inspectionAction(row,2,"SUBMIT",now),/REVISION_CONFLICT/));
 test("draft edit preserves original revision history",()=>{const revised=w.inspectionEdit(row,1,{...input,observations:["Correction"]},now);assert.equal(revised.revision,2);assert.equal(row.history.length,1);assert.equal(revised.history.length,2);});
 test("stale edit preserves original input",()=>assert.throws(()=>w.inspectionEdit(row,0,input,now),/REVISION_CONFLICT/));
 test("draft cannot seed case",()=>assert.throws(()=>w.findingDraft(row,["hypothesis"],"x",now)));
 row=w.inspectionAction(row,1,"SUBMIT",now);
 test("submit distinct from review",()=>assert.equal(row.status,"SUBMITTED"));
 test("self review denied",()=>assert.throws(()=>w.inspectionAction(row,2,"BEGIN_REVIEW",now,"demo-inspector"),/INDEPENDENT/));
 test("approval cannot skip review start",()=>assert.throws(()=>w.inspectionAction(row,2,"APPROVED",now,"demo-reviewer","x")));
 row=w.inspectionAction(row,2,"BEGIN_REVIEW",now,"demo-reviewer");
 test("reviewer reason mandatory",()=>assert.throws(()=>w.inspectionAction(row,3,"APPROVED",now,"demo-reviewer"," ")));
 test("return and revise preserve history",()=>{let r=w.inspectionAction(row,3,"RETURNED",now,"demo-reviewer","clarify");r=w.inspectionAction(r,4,"REVISE",now);assert.equal(r.status,"DRAFT");assert.equal(r.history.length,5);});
 row=w.inspectionAction(row,3,"APPROVED",now,"demo-reviewer","reviewed record only");
 test("approved edit denied",()=>assert.throws(()=>w.inspectionEdit(row,4,input,now),/IMMUTABLE/));
 test("approved not silently editable",()=>assert.throws(()=>w.inspectionAction(row,4,"SUBMIT",now)));
 let finding=w.findingDraft(row,["Human hypothesis"],"case:synthetic",now);
 test("frozen inspection version retained",()=>assert.equal(finding.inspectionRevision,4));
 test("max20 hypotheses",()=>assert.throws(()=>w.findingDraft(row,Array(21).fill("x"),"x",now)));
 test("blank hypothesis rejected",()=>assert.throws(()=>w.findingDraft(row,[" "],"x",now)));
 test("changed evidence blocks submission",()=>assert.throws(()=>w.findingAction(finding,{...row,revision:5},1,"SUBMIT",now),/EVIDENCE_VERSION/));
 finding=w.findingAction(finding,row,1,"SUBMIT",now);
 test("case self review denied",()=>assert.throws(()=>w.findingAction(finding,row,2,"APPROVED",now),/INDEPENDENT/));
 finding=w.findingAction(finding,row,2,"APPROVED",now,"demo-reviewer");
 const fields={action:"Propose further human inspection",priority:"NORMAL",pic:"team:demo",target:"2026-10-08",wo:"maintenance:SYNTHETIC:WO-A"};
 test("unapproved case cannot seed proposal",()=>assert.throws(()=>w.proposalDraft({...finding,status:"DRAFT"},"x",now,fields)));
 test("existing WO exact reference only",()=>assert.throws(()=>w.proposalDraft(finding,"x",now,{...fields,wo:"invented"})));
 test("WO cross-asset blocked",()=>assert.throws(()=>w.proposalDraft({...finding,asset:"asset:SYNTHETIC:B"},"x",now,fields)));
 let p=w.proposalDraft(finding,"recommendation:synthetic",now,fields);
 test("changed case rejected",()=>assert.throws(()=>w.proposalAction(p,{...finding,revision:4},1,"SUBMIT",now),/REVIEWED_CASE_CHANGED/));
 p=w.proposalAction(p,finding,1,"SUBMIT",now);
 test("action board awaiting review",()=>assert.equal(w.actionBoard([p],now).awaiting_review.length,1));
 test("recommendation self review blocked",()=>assert.throws(()=>w.proposalAction(p,finding,2,"APPROVED",now)));
 p=w.proposalAction(p,finding,2,"APPROVED",now,"demo-reviewer");
 test("overdue is local followup only",()=>assert.equal(w.actionBoard([p],now).overdue.length,1));
 for(const action of ["PLANNED","IN_PROGRESS","COMPLETED"])p=w.proposalAction(p,finding,p.revision,action,now);
 test("completed is not verified",()=>assert.equal(w.actionBoard([p],now).awaiting_verification.length,1));
 test("completion needs independent reviewer and evidence",()=>{assert.throws(()=>w.proposalAction(p,finding,p.revision,"VERIFIED",now));assert.throws(()=>w.proposalAction(p,finding,p.revision,"VERIFIED",now,"demo-reviewer"));});
 p=w.proposalAction(p,finding,p.revision,"VERIFIED",now,"demo-reviewer",row);
 test("WO ref remains informational unchanged",()=>assert.equal(p.wo,fields.wo));
 test("history retained",()=>assert.equal(p.history.length,7));
 const view=readFileSync("components/EngineeringWorkflow.tsx","utf8"),route=readFileSync("app/engineering/workflow/page.tsx","utf8");
 test("no API calls or browser authority",()=>assert.ok(!/fetch\(|axios|localStorage|Authorization|dangerouslySetInnerHTML/.test(view)));
 test("development-only gate",()=>assert.ok(route.includes('if(mode!=="DEMO")')&&route.includes('notFound()')));
 test("unknown health and clear synthetic labels",()=>assert.ok(view.includes("NOT ASSESSED")&&view.includes("SYNTHETIC LOCAL DEMO")&&view.includes("quality does not prove freshness")));
 test("unsaved input protected",()=>assert.ok(view.includes("beforeunload")&&view.includes("dirty&&!window.confirm")));
 test("all integrated screens",()=>{for(const x of ["Asset Health 360","PdM Center","Engineering Cases","Recommendations","Action Board"])assert.ok(view.includes(x));});
 console.log(`Workflow frontend checks passed: ${count}`);
}finally{rmSync(output,{recursive:true,force:true});}
