"""Machine-readable Phase-1 product gates; software tests are a separate audit."""
from enum import StrEnum
from datetime import datetime
from typing import Literal
from src.domain.condition_evidence import EvidenceModel
from src.domain.integration_status import CoverageSummary

class Verdict(StrEnum):
    PASS="PASS"
    PARTIAL="PARTIAL"
    BLOCKED="BLOCKED"
    UNKNOWN="UNKNOWN"

class GateId(StrEnum):
    MAXIMO="P1-MAXIMO-CURRENT"
    MART="P1-MART-CURRENT"
    PI_COLLECTOR="P1-PI-COLLECTOR-CURRENT"
    GOVERNANCE="P1-MART-GOVERNANCE-READY"
    CONDITION_SCHEMA="P1-CONDITION-SCHEMA-READY"
    MAPPING="P1-IDENTITY-MAPPING-READY"
    SIGNAL_SELECTION="P1-SIGNAL-SELECTION-READY"
    CONDITION_PROJECTION="P1-CONDITION-PROJECTION-READY"
    INTEGRATION_STATUS="P1-INTEGRATION-STATUS-READY"

class GateReason(StrEnum):
    LOCAL_EVIDENCE_CURRENT="LOCAL_EVIDENCE_CURRENT"
    READER_SCHEMA_COMPATIBLE="READER_SCHEMA_COMPATIBLE"
    VERIFIED_PILOT_AVAILABLE="VERIFIED_PILOT_AVAILABLE"
    APPROVED_PILOT_SIGNALS_AVAILABLE="APPROVED_PILOT_SIGNALS_AVAILABLE"
    COMPLETE_PILOT_PROJECTION="COMPLETE_PILOT_PROJECTION"
    STATUS_CONTRACT_VALID="STATUS_CONTRACT_VALID"
    HUMAN_CROSSWALK_REQUIRED="HUMAN_CROSSWALK_REQUIRED"
    AMBIGUOUS_MAPPING="AMBIGUOUS_MAPPING"
    GOVERNANCE_SCHEMA_NOT_READY="GOVERNANCE_SCHEMA_NOT_READY"
    CONDITION_SCHEMA_NOT_READY="CONDITION_SCHEMA_NOT_READY"
    LOCAL_EVIDENCE_UNAVAILABLE="LOCAL_EVIDENCE_UNAVAILABLE"
    LOCAL_EVIDENCE_STALE="LOCAL_EVIDENCE_STALE"
    LOCAL_EVIDENCE_DEGRADED="LOCAL_EVIDENCE_DEGRADED"
    UNKNOWN_FRESHNESS_POLICY="UNKNOWN_FRESHNESS_POLICY"
    UNKNOWN_TIMESTAMP="UNKNOWN_TIMESTAMP"
    UNKNOWN_MAPPING_READINESS="UNKNOWN_MAPPING_READINESS"
    NO_APPROVED_SIGNALS="NO_APPROVED_SIGNALS"
    PARTIAL_SIGNAL_SET="PARTIAL_SIGNAL_SET"
    SOURCE_STALE="SOURCE_STALE"
    PROJECTION_STALE="PROJECTION_STALE"
    UNKNOWN_SOURCE_OR_PROJECTION_FRESHNESS="UNKNOWN_SOURCE_OR_PROJECTION_FRESHNESS"
    QUALITY_NOT_ACCEPTED="QUALITY_NOT_ACCEPTED"
    PROJECTION_NOT_AVAILABLE="PROJECTION_NOT_AVAILABLE"
    PROJECTION_DEGRADED="PROJECTION_DEGRADED"
    STATUS_CONTRACT_INVALID="STATUS_CONTRACT_INVALID"

class ReadinessGate(EvidenceModel):
    gate: GateId
    verdict: Verdict
    reason: GateReason

class Phase1Readiness(EvidenceModel):
    contract_version: Literal["1.0"]="1.0"
    scope: Literal["PHASE_1_PRODUCT_PILOT"]="PHASE_1_PRODUCT_PILOT"
    evidence_origin: Literal["LOCAL_RUNTIME","OPERATOR_DOCUMENT"]="LOCAL_RUNTIME"
    observed_at: datetime
    verdict: Verdict
    gates: tuple[ReadinessGate,...]
    coverage: CoverageSummary
