"""Private operator failure vocabulary; never serialize source exception text."""
from enum import StrEnum

class SourceFailureCode(StrEnum):
    AUTH_FAILED = "SOURCE_AUTH_FAILED"
    TLS_FAILED = "SOURCE_TLS_FAILED"
    TIMEOUT = "SOURCE_TIMEOUT"
    CONNECT_FAILED = "SOURCE_CONNECT_FAILED"
    HTTP_ERROR = "SOURCE_HTTP_ERROR"
    CONTRACT_INVALID = "SOURCE_CONTRACT_INVALID"
    BUDGET_EXHAUSTED = "SOURCE_BUDGET_EXHAUSTED"
    OPERATION_REJECTED = "SOURCE_OPERATION_REJECTED"
    CAUSE_UNKNOWN = "SOURCE_CAUSE_UNKNOWN"
