'use client';
import {type FormEvent,useState} from 'react';
import type {CaseDraft} from '../lib/case-records';
import {investigationFields} from '../lib/case-records';
import {Button,InputControl} from './ui';
export default function CaseForm({initial,assets,busy,onSave,onCancel,editing=false}:{initial:CaseDraft;assets:string[];busy:boolean;onSave:(draft:CaseDraft)=>Promise<void>;onCancel:()=>void;editing?:boolean}){
 const [draft,setDraft]=useState(initial);
 function text(key:typeof investigationFields[number]){return draft.investigation[key].join('\n');}
 async function submit(e:FormEvent){e.preventDefault();await onSave(draft);}
 return <form className="engineering-form" onSubmit={submit} aria-busy={busy}><fieldset disabled={busy}><legend>{editing?'Edit draft case':'Create Engineering Case'}</legend><div className="filter-grid"><InputControl id="case-title" label="Case title" required maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><label>Permitted QA asset<select required disabled={editing} value={draft.canonical_asset_id} onChange={e=>setDraft({...draft,canonical_asset_id:e.target.value})}>{assets.map(id=><option key={id}>{id}</option>)}</select></label><label>Case category<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{['INVESTIGATION','MAINTENANCE','CONDITION'].map(x=><option key={x}>{x}</option>)}</select></label><label>Human priority (not risk)<select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}>{['LOW','NORMAL','HIGH'].map(x=><option key={x}>{x}</option>)}</select></label><InputControl id="case-assigned" label="Assigned engineer reference (optional)" maxLength={160} value={draft.assigned_engineer??''} onChange={e=>setDraft({...draft,assigned_engineer:e.target.value||null})}/></div><label htmlFor="case-problem">Problem statement<textarea id="case-problem" required maxLength={12000} value={draft.problem_statement} onChange={e=>setDraft({...draft,problem_statement:e.target.value})}/></label><label htmlFor="case-context">Operating context<textarea id="case-context" maxLength={6000} value={draft.investigation.operating_context} onChange={e=>setDraft({...draft,investigation:{...draft.investigation,operating_context:e.target.value}})}/></label><div className="product-context-grid">{investigationFields.map(key=><label key={key} htmlFor={'case-'+key}>{key.replaceAll('_',' ')} · one item per line, up to 20<textarea id={'case-'+key} value={text(key)} onChange={e=>setDraft({...draft,investigation:{...draft.investigation,[key]:e.target.value===''?[]:e.target.value.split('\n')}})}/></label>)}</div><p className="section-note">Observations and hypotheses remain separate human statements. Blank lists are allowed; remove empty lines before saving. No condition score is generated.</p><div className="engineering-actions"><Button type="submit" variant="primary">{busy?'Saving…':'Save case'}</Button><Button onClick={onCancel}>Cancel form</Button></div></fieldset></form>;
}
