'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import type {CaseRecord,CaseDraft} from '../lib/case-records';
import {caseDraft,emptyDraft,investigationFields} from '../lib/case-records';
import type {QaSession} from '../lib/product-records';
import {validRecordId} from '../lib/product-records';
import {engineeringRequest} from '../lib/engineering-http';
import {useQaRecords} from './useQaRecords';
import {useQaCommand} from './useQaCommand';
import QaProductBoundary from './QaProductBoundary';
import CaseForm from './CaseForm';
import {Button,EmptyState,Feedback,InputControl,PageHeader,Pagination,SectionCard,StatusBadge,TableFrame} from './ui';
export default function CaseWorkspace({enabled}:{enabled:boolean}){
 const [offset,setOffset]=useState(0),[asset,setAsset]=useState(''),[status,setStatus]=useState('');
 const qa=useQaRecords<CaseRecord>('cases',enabled,offset,`${asset?'&asset_id='+encodeURIComponent(asset):''}${status?'&status='+status:''}`);
 return <div className="product-workspace"><PageHeader eyebrow="Engineering · SYNTHETIC QA" title="Engineering Cases" description="Structured investigation, evidence and independent record review. Factual screens remain independently accessible." actions={<><Link className="button secondary" href="/engineering/advisories">Advisories →</Link><Link className="button secondary" href="/engineering/inbox">Recipient inbox →</Link></>}/><QaProductBoundary state={qa.state} reload={qa.reload}/>{qa.state==='ready'&&qa.page&&qa.session&&<><SectionCard><div className="filter-grid"><label>Permitted asset filter<select value={asset} onChange={e=>{setAsset(e.target.value);setOffset(0);}}><option value="">All permitted assets</option>{qa.session.asset_ids.map(id=><option key={id}>{id}</option>)}</select></label><label>Case status filter<select value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}}><option value="">All case states</option>{['DRAFT','IN_REVIEW','APPROVED','REJECTED'].map(x=><option key={x}>{x}</option>)}</select></label></div><p>{qa.page.total} authorized cases · server-filtered population</p></SectionCard><CaseBody key={qa.session.subject} rows={qa.page.items} session={qa.session} reload={qa.reload}/><SectionCard><Pagination meta={qa.page} onChange={setOffset}/></SectionCard></>}</div>;
}
function CaseBody({rows,session,reload}:{rows:CaseRecord[];session:QaSession;reload:()=>void}){
 const [selected,setSelected]=useState<string|null>(null),[creating,setCreating]=useState(false);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('record');if(validRecordId(id))setSelected(id);},[]);
 const cmd=useQaCommand(session,reload);
 async function create(draft:CaseDraft){const row=await cmd.run<CaseRecord>('cases','POST',{draft});if(row){setCreating(false);setSelected(row.case_id);reload();}}
 return <>{cmd.error&&<Feedback error>{cmd.error}</Feedback>}{cmd.notice&&<Feedback>{cmd.notice}</Feedback>}<SectionCard><div className="section-heading"><h2>Case register</h2>{session.roles.includes('AUTHOR')&&<Button variant="primary" onClick={()=>setCreating(true)}>New case</Button>}</div>{rows.length?<TableFrame label="Authorized Engineering case register" minWidth={680}><table><thead><tr><th>Case / canonical QA asset</th><th>Workflow</th><th>Revision / updated at</th></tr></thead><tbody>{rows.map(row=><tr key={row.case_id}><td><Button onClick={()=>{setSelected(row.case_id);window.history.replaceState({},'',`?record=${encodeURIComponent(row.case_id)}`);}}>{row.title}</Button><small className="table-subtext">{row.case_id}<br/>{row.canonical_asset_id}</small></td><td><StatusBadge mode="raw-neutral" value={row.status}/></td><td>{row.revision}<small className="table-subtext">{row.updated_at}</small></td></tr>)}</tbody></table></TableFrame>:<EmptyState title="No authorized cases match the server filters."/>}</SectionCard>{creating&&<SectionCard><CaseForm initial={emptyDraft(session.asset_ids[0]??'')} assets={session.asset_ids} busy={cmd.busy} onSave={create} onCancel={()=>setCreating(false)}/></SectionCard>}{selected&&<CaseDetail key={selected} id={selected} session={session} onExpired={reload}/>}</>;
}
function CaseDetail({id,session,onExpired}:{id:string;session:QaSession;onExpired:()=>void}){
 const [row,setRow]=useState<CaseRecord|null>(null),[failed,setFailed]=useState(false),[editing,setEditing]=useState(false),[reason,setReason]=useState(''),[note,setNote]=useState(''),[kind,setKind]=useState('ASSET'),[evidenceId,setEvidenceId]=useState(''),[history,setHistory]=useState<{revision:number;action:string;actor:string;occurred_at?:string;reason?:string}[]|null>(null),[historyOffset,setHistoryOffset]=useState(0),[rationale,setRationale]=useState(''),[action,setAction]=useState('');
 const cmd=useQaCommand(session,onExpired);
 useEffect(()=>{let active=true;engineeringRequest('cases/'+encodeURIComponent(id)).then(x=>{if(active)setRow(x as CaseRecord);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[id]);
 async function latest(){try{setRow(await engineeringRequest('cases/'+encodeURIComponent(id)) as CaseRecord);setFailed(false);}catch{setRow(null);setFailed(true);onExpired();}}
 async function change(endpoint:string,payload:Record<string,unknown>={}){if(!row)return;const next=await cmd.run<CaseRecord>(`cases/${encodeURIComponent(id)}/${endpoint}`,'POST',{expected_revision:row.revision,...payload});if(next){setRow(next);setHistory(null);}}
 async function save(draft:CaseDraft){if(!row)return;const next=await cmd.run<CaseRecord>('cases/'+encodeURIComponent(id),'PUT',{expected_revision:row.revision,draft});if(next){setRow(next);setEditing(false);setHistory(null);}}
 async function readHistory(offset:number){try{setHistory(await engineeringRequest(`cases/${encodeURIComponent(id)}/history?offset=${offset}&limit=25`) as typeof history);setHistoryOffset(offset);}catch{setHistory(null);setFailed(true);onExpired();}}
 async function recommend(){if(!row)return;const result=await cmd.run<{record_id:string}>('recommendations','POST',{draft:{canonical_asset_id:row.canonical_asset_id,case_ref:row.case_id,rationale,proposed_action:action,priority:'NORMAL',evidence_selections:row.evidence.map(e=>({kind:e.kind,record_id:e.record_id,mode:'FROZEN_SNAPSHOT'}))}});if(result)window.location.assign('/recommendations?record='+encodeURIComponent(result.record_id));}
 if(!row)return <SectionCard>{failed?<Feedback error>Case unavailable or access denied. No substitute record.</Feedback>:<p role="status">Reading authorized case…</p>}</SectionCard>;
 const author=session.roles.includes('AUTHOR')&&(row.created_by===session.subject||row.assigned_engineer===session.subject),reviewer=session.roles.includes('REVIEWER');
 return <SectionCard><div className="section-heading"><h2>{row.title}</h2><StatusBadge mode="raw-neutral" value={row.status}/></div><p className="section-note">{row.case_id} · {row.canonical_asset_id} · Revision {row.revision} · SYNTHETIC QA</p>{cmd.error&&<Feedback error>{cmd.error}</Feedback>}{cmd.notice&&<Feedback>{cmd.notice}</Feedback>}<Button onClick={latest} disabled={cmd.busy}>Read latest revision (keep unsaved form)</Button><h3>Problem statement</h3><p className="engineering-prose">{row.problem_statement}</p><h3>Operating context</h3><p>{row.investigation.operating_context||'UNKNOWN'}</p><div className="product-context-grid">{investigationFields.map(key=><div key={key}><h3>{key.replaceAll('_',' ')}</h3>{row.investigation[key].length?<ul>{row.investigation[key].map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>NOT RECORDED</p>}</div>)}</div><h3>Evidence references</h3>{row.evidence.length?<TableFrame label="Case evidence provenance" minWidth={550}><table><thead><tr><th>Kind / record</th><th>Snapshot availability</th><th>Version</th></tr></thead><tbody>{row.evidence.map(e=><tr key={e.reference_id}><td>{e.kind}<small className="table-subtext">{e.record_id}</small></td><td>{e.mode} · {e.snapshot?.label??'Live reference'}<small className="table-subtext">{e.snapshot?.availability??'UNKNOWN'}</small></td><td className="identifier">{e.stable_version}</td></tr>)}</tbody></table></TableFrame>:<p>Evidence NOT LINKED.</p>}<h3>Notes</h3>{row.notes.map((n,i)=><p key={i}>{n.text}</p>)}<h3>Independent review</h3><p>{row.review?`${row.review.decision} · ${row.review.reviewer} · ${row.review.decided_at} · ${row.review.rationale}`:'NOT REVIEWED'}</p>
 {author&&row.status==='DRAFT'&&<><Button onClick={()=>setEditing(true)}>Edit case</Button>{editing&&<CaseForm initial={caseDraft(row)} editing assets={session.asset_ids} busy={cmd.busy} onSave={save} onCancel={()=>setEditing(false)}/>}<div className="filter-grid"><label>Evidence kind<select value={kind} onChange={e=>setKind(e.target.value)}>{['ASSET','MAINTENANCE','WORK_ORDER','FMEA','RCFA','CONDITION','DATA_TRUST','MANUAL_INSPECTION'].map(x=><option key={x}>{x}</option>)}</select></label><InputControl id="case-evidence-id" label="Exact evidence record reference" value={evidenceId} onChange={e=>setEvidenceId(e.target.value)}/><Button disabled={cmd.busy||!evidenceId.trim()} onClick={()=>change('evidence',{kind,record_id:evidenceId,mode:'FROZEN_SNAPSHOT'})}>Link frozen evidence</Button><InputControl id="case-note" label="Case note" value={note} maxLength={12000} onChange={e=>setNote(e.target.value)}/><Button disabled={cmd.busy||!note.trim()} onClick={()=>change('notes',{text:note})}>Add note</Button></div><Button variant="primary" disabled={cmd.busy} onClick={()=>change('submit')}>Submit case for review</Button></>}
 <InputControl id="case-reason" label="Review / revision rationale" value={reason} maxLength={6000} onChange={e=>setReason(e.target.value)}/><div className="engineering-actions">{reviewer&&row.status==='IN_REVIEW'&&['APPROVED','REJECTED'].map(decision=><Button key={decision} disabled={cmd.busy||!reason.trim()} onClick={()=>change('review',{decision,reason})}>{decision==='APPROVED'?'Approve case':'Reject case'}</Button>)}{author&&row.status==='REJECTED'&&<Button disabled={cmd.busy||!reason.trim()} onClick={()=>change('revise',{reason})}>Revise rejected case</Button>}{reviewer&&row.status==='APPROVED'&&<Button disabled={cmd.busy||!reason.trim()} onClick={()=>change('reopen',{reason})}>Reopen case (invalidates downstream eligibility)</Button>}</div>
 {author&&row.status==='APPROVED'&&<div className="engineering-form"><h3>Create linked NADI recommendation</h3><p>Uses this reviewed case and its exact frozen evidence references. Not maintenance authorization.</p><InputControl id="rec-rationale" label="Recommendation rationale" value={rationale} maxLength={6000} onChange={e=>setRationale(e.target.value)}/><InputControl id="rec-action" label="Proposed local follow-up" value={action} maxLength={6000} onChange={e=>setAction(e.target.value)}/><Button disabled={cmd.busy||!rationale.trim()||!action.trim()||!row.evidence.length} onClick={recommend}>Create linked recommendation</Button></div>}
 <div className="engineering-actions"><Link className="button secondary" href="/recommendations">Recommendations →</Link><Link className="button secondary" href="/engineering/advisories">Advisories →</Link><Link className="button secondary" href="/engineering/local">Diagnostic QA workbench →</Link><Button onClick={()=>readHistory(0)}>Read case history</Button></div>{history&&<><h3>Immutable case history</h3>{history.map(e=><p key={e.revision}>Revision {e.revision} · {e.action} · {e.actor} · {e.occurred_at??'UNKNOWN'} · {e.reason??'No reason recorded'}</p>)}<Button disabled={historyOffset===0} onClick={()=>readHistory(Math.max(0,historyOffset-25))}>Previous revisions</Button><Button disabled={history.length<25||historyOffset>=10000} onClick={()=>readHistory(historyOffset+25)}>Next revisions</Button></>}
 </SectionCard>;
}
