'use client';
import {useEffect,useState} from 'react';
import {PageHeader,SectionCard} from './ui';
import {engineeringRequest,EngineeringHttpError} from '../lib/engineering-http';
type Document=Record<string,unknown>;
export default function EngineeringQa(){
 const [proof,setProof]=useState(''),[csrf,setCsrf]=useState(''),[session,setSession]=useState<Document|null>(null),[asset,setAsset]=useState('');
 const [resource,setResource]=useState('inspections'),[record,setRecord]=useState(''),[action,setAction]=useState(''),[payload,setPayload]=useState('{}');
 const [result,setResult]=useState<unknown>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[offset,setOffset]=useState(0);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function run(operation:()=>Promise<unknown>){setBusy(true);setError('');try{const value=await operation();setResult(value);return value;}catch(e){setError(e instanceof EngineeringHttpError?`${e.status}: ${e.code}. Input retained; reload revision before retrying.`:'Invalid input or unavailable response.');}finally{setBusy(false);}}
 async function login(){await run(async()=>{const value=await engineeringRequest('session','POST',{proof}) as {csrf_token:string};setCsrf(value.csrf_token);setProof('');const who=await engineeringRequest('session') as Document;setSession(who);return who;});}
 async function list(){await run(()=>engineeringRequest(`${resource}?offset=${offset}&limit=25`));}
 async function command(){await run(async()=>{const body=JSON.parse(payload);const value=await engineeringRequest(resource+(record?'/'+encodeURIComponent(record):'')+(action?'/'+action:''),record&&!action?'PUT':'POST',body,csrf);setDirty(false);return value;});}
 return <><PageHeader eyebrow="DEVELOPMENT / DISPOSABLE QA" title="Engineering backend workspace" description="Real HTTP and isolated persisted application records. Fixture source data is not operational plant evidence."/>
 <SectionCard><h2>Trusted session</h2><p>Identity is verified by the backend adapter. This form supplies an opaque proof, never an actor or role.</p><label>Verified test proof<input type="password" value={proof} onChange={e=>setProof(e.target.value)} autoComplete="off"/></label><button disabled={busy||!proof} onClick={login}>Establish session</button>{session&&<p>Subject: {String(session.subject)} · Roles: {JSON.stringify(session.roles)}</p>}<button disabled={busy||!session} onClick={()=>run(async()=>{const value=await engineeringRequest('session/logout','POST',{},csrf);setSession(null);setCsrf('');return value;})}>Revoke session</button></SectionCard>
 <SectionCard><h2>Asset Context / Asset Health 360</h2><label>Canonical asset<input value={asset} onChange={e=>setAsset(e.target.value)}/></label><button disabled={busy||!session||!asset} onClick={()=>run(()=>engineeringRequest('asset-context/'+encodeURIComponent(asset)))}>Read asset context</button><p>Assessment remains NOT ASSESSED. Source quality is separate from freshness and equipment health.</p></SectionCard>
 <SectionCard><h2>Inspections · Cases · Recommendations · Action Board</h2><label>Module<select value={resource} onChange={e=>{setResource(e.target.value);setOffset(0);}}><option value="inspections">Manual PdM inspections</option><option value="cases">Engineering Cases</option><option value="recommendations">Recommendations / Action Board</option></select></label><button disabled={busy||!session} onClick={list}>Load records</button><button disabled={offset===0||busy} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</button><button disabled={busy} onClick={()=>setOffset(offset+25)}>Next</button><p>Offset {offset}. Empty, unavailable and permission-denied responses are explicit.</p>
 <label>Record ID (empty to create)<input value={record} onChange={e=>setRecord(e.target.value)}/></label><label>Action<select value={action} onChange={e=>setAction(e.target.value)}>{['','submit','begin_review','review','revise','reopen','evidence','notes','followup','verify_completion'].map(a=><option key={a} value={a}>{a||'Create / edit draft'}</option>)}</select></label><label>Canonical command JSON<textarea rows={14} value={payload} onChange={e=>{setPayload(e.target.value);setDirty(true);}} style={{width:'100%',fontFamily:'monospace'}}/></label><p>Include request_id and expected_revision for changes. Server enforces review independence and exact same-asset evidence. Recommendations never create or update Maximo WO.</p><button disabled={busy||!session} onClick={command}>Send controlled command</button><button disabled={busy||!session||!record} onClick={()=>run(()=>engineeringRequest(`${resource}/${encodeURIComponent(record)}/history`))}>Read immutable history</button></SectionCard>
 <SectionCard><h2>Response and provenance</h2>{busy&&<p role="status">Loading…</p>}{error&&<p role="alert">{error}</p>}{result===null?<p>No evidence loaded. UNKNOWN.</p>:<pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(result,null,2)}</pre>}</SectionCard></>;
}
