"use client";
import {useEffect,useState,type ReactNode} from "react";
import {PageHeader,SectionCard as SharedSectionCard,StatusBadge,EmptyState} from "./ui";
import {methods,enteredValue,type Method,type InspectionInput} from "../lib/manual-pdm";
import {parseHypotheses} from "../lib/engineering";
import {inspectionDraft,inspectionEdit,inspectionAction,findingDraft,findingAction,proposalDraft,proposalAction,actionBoard,type Inspection,type Finding,type Proposal} from "../lib/engineering-workflow";
import styles from "./EngineeringWorkflow.module.css";

const views=["Asset Health 360","PdM Center","Engineering Cases","Recommendations","Action Board"] as const;
const assets=[{id:"asset:SYNTHETIC:A",name:"DEMO • Feeder A",location:"DEMO boiler area",parent:"DEMO fuel system"},
  {id:"asset:SYNTHETIC:B",name:"DEMO • Pump B",location:"DEMO auxiliary area",parent:"DEMO cooling system"}];
const stamp="2026-10-09T00:00:00Z";
function SectionCard({title,eyebrow,children}:{title:string;eyebrow:string;children:ReactNode}){
  return <SharedSectionCard><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</SharedSectionCard>;
}
export default function EngineeringWorkflow(){
  const [view,setView]=useState<typeof views[number]>("Asset Health 360"),[asset,setAsset]=useState(assets[0].id);
  const [inspections,setInspections]=useState<Inspection[]>([]),[findings,setFindings]=useState<Finding[]>([]),[proposals,setProposals]=useState<Proposal[]>([]);
  const [method,setMethod]=useState<Method>("VIBRATION"),[quantity,setQuantity]=useState("reported quantity"),[value,setValue]=useState(""),[unit,setUnit]=useState("");
  const [kind,setKind]=useState<"NUMERIC"|"TEXT"|"BOOLEAN"|"UNKNOWN">("UNKNOWN"),[time,setTime]=useState(stamp),[context,setContext]=useState("");
  const [observation,setObservation]=useState(""),[hypothesis,setHypothesis]=useState(""),[filename,setFilename]=useState("");
  const [reason,setReason]=useState(""),[dirty,setDirty]=useState(false),[error,setError]=useState("");
  const [editing,setEditing]=useState<{id:string;revision:number}|null>(null);
  const [action,setAction]=useState(""),[priority,setPriority]=useState<Proposal["priority"]>("NORMAL"),[pic,setPic]=useState("demo-maintenance-team"),[target,setTarget]=useState(""),[wo,setWo]=useState(false);
  const [search,setSearch]=useState(""),[filter,setFilter]=useState("ALL");
  useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",leave);return()=>window.removeEventListener("beforeunload",leave);},[dirty]);
  const changeView=(next:typeof view)=>{if(dirty&&!window.confirm("Discard unsaved inspection input?"))return;setDirty(false);setView(next);setError("");};
  const now=()=>new Date().toISOString(),safe=(fn:()=>void)=>{try{fn();setError("");}catch(e){setError(e instanceof Error?e.message:"Candidate validation failed.");}};
  const current=assets.find(x=>x.id===asset)!,rows=inspections.filter(x=>x.asset===asset),cases=findings.filter(x=>x.asset===asset),recommendations=proposals.filter(x=>x.asset===asset);
  const approved=rows.find(x=>x.status==="APPROVED"),approvedCase=cases.find(x=>x.status==="APPROVED"),board=actionBoard(recommendations,now());
  const reviewReason=()=>{if(!reason.trim())throw Error("Enter a reviewer reason before a simulated decision.");return reason;};
  const inspectionStep=(row:Inspection,step:Parameters<typeof inspectionAction>[2])=>safe(()=>{const actor=["BEGIN_REVIEW","APPROVED","RETURNED","REJECTED"].includes(step)?"demo-reviewer":"demo-inspector";
    const next=inspectionAction(row,row.revision,step,now(),actor,["APPROVED","RETURNED","REJECTED"].includes(step)?reviewReason():"Demo workflow");setInspections(all=>all.map(x=>x.id===row.id?next:x));});
  const caseStep=(row:Finding,step:Parameters<typeof findingAction>[3])=>safe(()=>{if(step!=="SUBMIT")reviewReason();const source=inspections.find(x=>x.id===row.inspection);if(!source)throw Error("Evidence missing");
    const next=findingAction(row,source,row.revision,step,now(),step==="SUBMIT"?"demo-inspector":"demo-reviewer",step==="SUBMIT"?"Submitted demo finding":reason);setFindings(all=>all.map(x=>x.id===row.id?next:x));});
  const proposalStep=(row:Proposal,step:Parameters<typeof proposalAction>[3])=>safe(()=>{if(["APPROVED","REJECTED","VERIFIED"].includes(step))reviewReason();const source=findings.find(x=>x.id===row.caseId);if(!source)throw Error("Reviewed case missing");
    const next=proposalAction(row,source,row.revision,step,now(),["APPROVED","REJECTED","VERIFIED"].includes(step)?"demo-reviewer":"demo-inspector",approved??null,["APPROVED","REJECTED","VERIFIED"].includes(step)?reason:"Local demo follow-up");setProposals(all=>all.map(x=>x.id===row.id?next:x));});
  const history=(items:{revision:number;action:string;actor:string;at:string;reason:string}[])=><details><summary>Immutable local demo history ({items.length})</summary><ol>{items.map(x=><li key={x.revision}>r{x.revision} • {x.action} • {x.actor} • <time>{x.at}</time><p>{x.reason}</p></li>)}</ol></details>;
  return <div className={styles.workspace}>
    <PageHeader eyebrow="PHASE 2 / SYNTHETIC LOCAL DEMO" title={view} description="Development candidate • all records are synthetic browser-memory fixtures. No operational authentication or backend writes."/>
    <div className={styles.banner}><strong>DEMO • NOT OPERATIONAL</strong><p>Simulated independent reviewer controls are presentation fixtures, never browser-controlled authority. Source quality does not prove freshness or equipment health. No Maximo WO create, update, approval or closure. File storage disabled.</p></div>
    <div className={styles.toolbar}><label>Canonical asset<select aria-label="Canonical asset" value={asset} onChange={e=>{if(dirty&&!window.confirm("Discard unsaved inspection input?"))return;setAsset(e.target.value);setDirty(false);setEditing(null);setWo(false);}}>{assets.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><StatusBadge mode="raw-neutral" value="NOT ASSESSED"/><span className={styles.identifier}>{asset}</span></div>
    <nav className={styles.tabs} aria-label="Engineering workflow screens">{views.map(x=><button type="button" aria-pressed={view===x} key={x} onClick={()=>changeView(x)}>{x}</button>)}</nav>
    {error&&<p className={styles.error} role="alert">{error} Unsaved input has been retained.</p>}
    {view==="Asset Health 360"&&<>
      <div className={styles.grid}><SectionCard title="Asset context" eyebrow="SOURCE FACT / SYNTHETIC FIXTURE"><dl><dt>Identity</dt><dd>{current.id}</dd><dt>Location / parent</dt><dd>{current.location} / {current.parent}</dd><dt>Classification</dt><dd>UNKNOWN • no fabricated classification</dd><dt>Collected / source timestamp</dt><dd>{stamp} / {stamp}</dd><dt>Freshness / quality</dt><dd>UNKNOWN / UNKNOWN</dd></dl></SectionCard>
      <SectionCard title="Condition evidence" eyebrow="SYNTHETIC ACCEPTED EVIDENCE EXAMPLE">{asset===assets[0].id?<dl><dt>Signal / original unit</dt><dd>coal_flow / Ton/h</dd><dt>Value / type</dt><dd>12.5 / NUMERIC • synthetic only</dd><dt>Source / collection timestamp</dt><dd>{stamp} / {stamp}</dd><dt>PI quality flags</dt><dd>Good true • Questionable false • Substituted false • Annotated false</dd><dt>Freshness / mapping</dt><dd>UNKNOWN • synthetic VERIFIED fixture only</dd><dt>Provenance</dt><dd>NADI_CONDITION • frozen demo lineage</dd></dl>:<EmptyState title="UNMAPPED / NO APPROVED SIGNALS" detail="Condition evidence UNKNOWN. No healthy state inferred."/>}</SectionCard></div>
      <SectionCard title="Maintenance chronology" eyebrow="SOURCE FACT / LOCAL COPY EXAMPLE"><div className={styles.tableWrap}><table><thead><tr><th>Existing WO</th><th>Source status</th><th>Activity timestamp</th><th>Collection</th><th>Provenance</th></tr></thead><tbody>{asset===assets[0].id?<tr><td>maintenance:SYNTHETIC:WO-A</td><td>COMP • informational</td><td>{stamp}</td><td>{stamp}</td><td>CANONICAL_MART_LOCAL_COPY • DEMO</td></tr>:<tr><td colSpan={5}>EMPTY synthetic maintenance window; source coverage UNKNOWN</td></tr>}</tbody></table></div></SectionCard>
      <SectionCard title="Human evidence and follow-up" eyebrow="HUMAN INTERPRETATION / REVIEW DECISION"><p>{rows.length} demo inspections • {cases.length} demo cases • {recommendations.length} demo recommendations. These are browser-local counts.</p><p>Only APPROVED inspections may seed a finding. Review does not turn a hypothesis into source fact.</p><button onClick={()=>changeView("PdM Center")}>Open inspection workflow</button></SectionCard>
    </>}
    {view==="PdM Center"&&<>
      <div className={styles.methodTabs} aria-label="Inspection methods">{methods.map(x=><button key={x} type="button" aria-pressed={method===x} onClick={()=>{setMethod(x);setDirty(true);}}>{x.replaceAll("_"," ")}</button>)}</div>
      <SectionCard title="Manual inspection draft" eyebrow="INSPECTOR REPORTED / ENGINEER FIELDS PENDING"><form onSubmit={e=>{e.preventDefault();safe(()=>{const input:InspectionInput={canonical_asset_id:asset,method,method_version:"proposal-1",inspector_ref:"demo-inspector",inspected_at:time,quantity,value:enteredValue(value,kind),unit:unit||null,operating_context:context,observations:parseHypotheses(observation),interpretations:parseHypotheses(hypothesis)};
        if(editing){const existing=inspections.find(x=>x.id===editing.id);if(!existing)throw Error("Record missing");const row=inspectionEdit(existing,editing.revision,input,now(),filename);setInspections(all=>all.map(x=>x.id===row.id?row:x));}
        else {const row=inspectionDraft(input,`inspection:demo-${inspections.length+1}`,now(),filename);setInspections(all=>[...all,row]);}setEditing(null);setDirty(false);});}}>
        <div className={styles.grid}><label>Inspection timestamp (timezone required)<input value={time} onChange={e=>{setTime(e.target.value);setDirty(true);}} required/></label><label>Reported quantity<input value={quantity} onChange={e=>{setQuantity(e.target.value);setDirty(true);}} maxLength={120} required/></label><label>Value type<select aria-label="Value type" value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setDirty(true);}}>{["UNKNOWN","NUMERIC","TEXT","BOOLEAN"].map(x=><option key={x}>{x}</option>)}</select></label><label>Original measurement<input aria-label="Original measurement" value={value} disabled={kind==="UNKNOWN"} onChange={e=>{setValue(e.target.value);setDirty(true);}}/><small>UNKNOWN preserves null; blank numeric never becomes zero.</small></label><label>Original unit<input value={unit} onChange={e=>{setUnit(e.target.value);setDirty(true);}} maxLength={40}/></label><label>Attachment filename (metadata only)<input value={filename} onChange={e=>{setFilename(e.target.value);setDirty(true);}}/><small>No file is uploaded or stored.</small></label></div>
        <label>Operating context<textarea value={context} onChange={e=>{setContext(e.target.value);setDirty(true);}} maxLength={6000}/></label><div className={styles.grid}><label>Inspector observations (one per line)<textarea value={observation} onChange={e=>{setObservation(e.target.value);setDirty(true);}}/></label><label>HUMAN HYPOTHESIS (one per line)<textarea aria-label="HUMAN HYPOTHESIS (one per line)" value={hypothesis} onChange={e=>{setHypothesis(e.target.value);setDirty(true);}}/><small>Up to 20 nonblank entries, 2,000 code points each.</small></label></div><button type="submit">{editing?"Save inspection revision":"Save demo inspection draft"}</button>{dirty&&<small>Unsaved input • protected on navigation</small>}
      </form></SectionCard>
      <label>Independent reviewer reason<textarea aria-label="Independent reviewer reason" value={reason} onChange={e=>setReason(e.target.value)} maxLength={6000}/></label>
      <SectionCard title="Inspection detail & review queue" eyebrow="DEMO REVIEW DECISIONS">{!rows.length&&<EmptyState title="No local inspections yet"/>}{rows.map(row=><article className={styles.record} key={row.id}><h3>{row.id} <StatusBadge mode="raw-neutral" value={row.status}/></h3><p>{row.input.method} • r{row.revision} • {row.input.inspector_ref} • {row.input.inspected_at}</p><p>Reported measurement: {row.input.value===null?"UNKNOWN":String(row.input.value)} {row.input.unit??"unit UNKNOWN"} • quality UNKNOWN • freshness UNKNOWN</p><p>Observation: {row.input.observations.join("; ")||"UNKNOWN"}</p><p>HUMAN HYPOTHESIS: {row.input.interpretations.join("; ")||"UNKNOWN"}</p>{row.attachment&&<p>{row.attachment.filename} • {row.attachment.status}</p>}
        <div className={styles.actions}>{row.status==="DRAFT"&&<button onClick={()=>{if(dirty&&!window.confirm("Discard unsaved inspection input?"))return;setEditing({id:row.id,revision:row.revision});setMethod(row.input.method);setQuantity(row.input.quantity);setKind(row.input.value===null?"UNKNOWN":typeof row.input.value==="number"?"NUMERIC":typeof row.input.value==="boolean"?"BOOLEAN":"TEXT");setValue(row.input.value===null?"":String(row.input.value));setUnit(row.input.unit??"");setTime(row.input.inspected_at??stamp);setContext(row.input.operating_context);setObservation(row.input.observations.join("\n"));setHypothesis(row.input.interpretations.join("\n"));setFilename(row.attachment?.filename??"");setDirty(true);}}>Edit inspection draft</button>}{row.status==="DRAFT"&&<button onClick={()=>inspectionStep(row,"SUBMIT")}>Submit inspection</button>}{row.status==="SUBMITTED"&&<button onClick={()=>inspectionStep(row,"BEGIN_REVIEW")}>Simulate independent review start</button>}{row.status==="UNDER_REVIEW"&&["APPROVED","RETURNED","REJECTED"].map(x=><button key={x} onClick={()=>inspectionStep(row,x as "APPROVED"|"RETURNED"|"REJECTED")}>Simulate {x.toLowerCase()}</button>)}{["RETURNED","REJECTED"].includes(row.status)&&<button onClick={()=>inspectionStep(row,"REVISE")}>Revise returned inspection</button>}{row.status==="APPROVED"&&<span>Read-only approved revision • NOT ASSESSED</span>}</div>{history(row.history)}</article>)}</SectionCard>
    </>}
    {view==="Engineering Cases"&&<><SectionCard title="Investigation from reviewed evidence" eyebrow="HUMAN HYPOTHESIS"><p>Selected evidence: {approved?`${approved.id} r${approved.revision}`:"NO APPROVED INSPECTION"}. A frozen reviewed record preserves original units and time.</p><label>Investigation hypotheses (one per line)<textarea aria-label="Investigation hypotheses (one per line)" value={hypothesis} onChange={e=>{setHypothesis(e.target.value);setDirty(true);}}/></label><button disabled={!approved} onClick={()=>safe(()=>{if(!approved)return;setFindings(all=>[...all,findingDraft(approved,parseHypotheses(hypothesis),`case:demo-${findings.length+1}`,now())]);setDirty(false);})}>Create demo Engineering Case</button></SectionCard>
      <label>Independent reviewer reason<textarea aria-label="Independent reviewer reason" value={reason} onChange={e=>setReason(e.target.value)}/></label>{cases.map(row=><SectionCard title={row.id} eyebrow="REVIEWED FINDING / HUMAN INTERPRETATION" key={row.id}><StatusBadge mode="raw-neutral" value={row.status}/><p>{row.hypotheses.join("; ")||"No hypothesis supplied"}</p><p>Frozen inspection: {row.inspection} r{row.inspectionRevision}</p><div className={styles.actions}>{row.status==="DRAFT"&&<button onClick={()=>caseStep(row,"SUBMIT")}>Submit case</button>}{row.status==="IN_REVIEW"&&["APPROVED","REJECTED"].map(x=><button key={x} onClick={()=>caseStep(row,x as "APPROVED"|"REJECTED")}>Simulate case {x.toLowerCase()}</button>)}</div>{history(row.history)}</SectionCard>)}</>}
    {view==="Recommendations"&&<>
      <SectionCard title="NADI recommendation draft" eyebrow="PROPOSAL / NOT MAINTENANCE AUTHORIZATION"><p>Reviewed case: {approvedCase?.id??"NO APPROVED CASE"}</p><label>Proposed action<textarea value={action} onChange={e=>{setAction(e.target.value);setDirty(true);}} maxLength={6000}/></label><div className={styles.grid}><label>Priority<select value={priority} onChange={e=>{setPriority(e.target.value as typeof priority);setDirty(true);}}>{["LOW","NORMAL","HIGH"].map(x=><option key={x}>{x}</option>)}</select></label><label>Internal PIC reference<input value={pic} onChange={e=>{setPic(e.target.value);setDirty(true);}} maxLength={160}/></label><label>Target date<input type="date" value={target} onChange={e=>{setTarget(e.target.value);setDirty(true);}}/></label><label><input type="checkbox" disabled={asset!==assets[0].id} checked={wo} onChange={e=>{setWo(e.target.checked);setDirty(true);}}/>Link existing synthetic WO (informational)</label></div><button disabled={!approvedCase} onClick={()=>safe(()=>{if(!approvedCase)return;const row=proposalDraft(approvedCase,`recommendation:demo-${proposals.length+1}`,now(),{action,priority,pic,target:target||null,wo:wo?"maintenance:SYNTHETIC:WO-A":null});setProposals(all=>[...all,row]);setDirty(false);})}>Save demo recommendation</button></SectionCard>
      <div className={styles.toolbar}><label>Search<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Status filter<select value={filter} onChange={e=>setFilter(e.target.value)}>{["ALL","DRAFT","IN_REVIEW","APPROVED","REJECTED"].map(x=><option key={x}>{x}</option>)}</select></label><label>Independent reviewer reason<input aria-label="Independent reviewer reason" value={reason} onChange={e=>setReason(e.target.value)}/></label></div>
      {recommendations.filter(x=>(filter==="ALL"||x.status===filter)&&[x.id,x.action,x.pic].join(" ").toLowerCase().includes(search.toLowerCase())).map(row=><SectionCard key={row.id} title={row.id} eyebrow="NADI LOCAL FOLLOW-UP ONLY"><StatusBadge mode="raw-neutral" value={row.status}/><p>{row.action}</p><p>{row.priority} • {row.pic} • target {row.target??"UNKNOWN"} • follow-up {row.followup}</p><p>Existing WO: {row.wo??"none"} • no source mutation</p><div className={styles.actions}>{row.status==="DRAFT"&&<button onClick={()=>proposalStep(row,"SUBMIT")}>Submit recommendation</button>}{row.status==="IN_REVIEW"&&["APPROVED","REJECTED"].map(x=><button key={x} onClick={()=>proposalStep(row,x as "APPROVED"|"REJECTED")}>Simulate recommendation {x.toLowerCase()}</button>)}{row.status==="APPROVED"&&row.followup!=="VERIFIED"&&<button onClick={()=>proposalStep(row,({PROPOSED:"PLANNED",PLANNED:"IN_PROGRESS",IN_PROGRESS:"COMPLETED",COMPLETED:"VERIFIED",VERIFIED:"VERIFIED"} as const)[row.followup])}>{row.followup==="COMPLETED"?"Simulate independent completion verification":"Record local "+({PROPOSED:"planned",PLANNED:"in progress",IN_PROGRESS:"completed",COMPLETED:"completed",VERIFIED:"verified"} as const)[row.followup]}</button>}</div>{history(row.history)}</SectionCard>)}
    </>}
    {view==="Action Board"&&<><p>Counts below refer only to this asset’s synthetic browser-memory records.</p><div className={styles.grid}>{[["Awaiting recommendation review",board.awaiting_review],["Overdue local follow-up",board.overdue],["Awaiting completion verification",board.awaiting_verification]].map(([title,items])=><SectionCard key={title as string} title={title as string} eyebrow="DEMO ACTION SUMMARY">{(items as Proposal[]).length?(items as Proposal[]).map(row=><p key={row.id}>{row.id} • {row.pic} • {row.target??"date UNKNOWN"}</p>):<EmptyState title="No matching demo records"/>}</SectionCard>)}</div><SectionCard title="Unresolved evidence" eyebrow="UNKNOWN / NOT ASSESSED"><p>{rows.filter(x=>x.status!=="APPROVED").length} unapproved demo inspections. Freshness policy UNKNOWN. Method-specific engineering fields pending. No health or predictive score.</p><button onClick={()=>changeView("Recommendations")}>Open recommendation follow-up</button></SectionCard></>}
  </div>;
}
