"use client";
import {useEffect,useRef,useState} from "react";
import {engineeringRequest,EngineeringHttpError} from "../lib/engineering-http";
import type {HumanRecord} from "../lib/product-records";
import {SectionCard,LoadingState,Button,TableFrame} from "./ui";
import type {ReactNode} from "react";
// Exact authorized detail + separately bounded immutable history, not a browser-memory lookup.
export default function QaRecordReader<T extends HumanRecord>({resource,id,render,onInvalid}:{resource:"inspections"|"recommendations";id:string;render:(row:T)=>ReactNode;onInvalid:()=>void}) {
 const generation=useRef(0);
 const [row,setRow]=useState<T|null>(null),[failed,setFailed]=useState(false),[refresh,setRefresh]=useState(0),[history,setHistory]=useState<{revision:number;action:string;actor:string;occurred_at?:string;reason?:string}[]|null>(null),[historyError,setHistoryError]=useState(false),[historyOffset,setHistoryOffset]=useState(0),[historyBusy,setHistoryBusy]=useState(false);
 useEffect(()=>{let active=true;const epoch=++generation.current;setRow(null);setHistory(null);setHistoryBusy(false);setHistoryError(false);setHistoryOffset(0);setFailed(false);engineeringRequest(`${resource}/${encodeURIComponent(id)}`).then(next=>{if(active)setRow(next as T);}).catch(error=>{if(active){setFailed(true);if(error instanceof EngineeringHttpError&&error.status===401)onInvalid();}});return()=>{active=false;generation.current=epoch+1;};},[resource,id,refresh,onInvalid]);
 async function readHistory(offset:number){const epoch=generation.current;setHistoryBusy(true);setHistory(null);setHistoryError(false);try{const result=await engineeringRequest(`${resource}/${encodeURIComponent(id)}/history?offset=${offset}&limit=25`);if(epoch!==generation.current)return;if(!Array.isArray(result))throw new Error();setHistory(result);setHistoryOffset(offset);}catch(error){if(epoch!==generation.current)return;setHistoryError(true);if(error instanceof EngineeringHttpError&&error.status===401)onInvalid();}finally{if(epoch===generation.current)setHistoryBusy(false);}}
 return <>{!row&&!failed&&<LoadingState label="Reading exact authorized record…"/>}{failed&&<SectionCard><p role="alert">Exact record unavailable or access denied. No record substituted.</p><Button onClick={()=>setRefresh(n=>n+1)}>Retry record</Button></SectionCard>}{row&&<>{render(row)}<SectionCard><h2>Immutable revision / audit history</h2><Button onClick={()=>readHistory(0)} disabled={historyBusy}>Read history</Button>{historyBusy&&<LoadingState label="Reading immutable history…"/>}{historyError&&<p role="alert">History UNAVAILABLE; no absence claim.</p>}{history&&<><TableFrame minWidth={480} label="Immutable revision history"><table><thead><tr><th>Revision</th><th>Recorded action</th><th>Actor reference</th><th>Recorded at / reason</th></tr></thead><tbody>{history.map((event,i)=><tr key={i}><td>{event.revision}</td><td>{event.action??"UNKNOWN"}</td><td>{event.actor??"UNKNOWN"}</td><td>{event.occurred_at??"UNKNOWN"}<small className="table-subtext">{event.reason??"No reason recorded"}</small></td></tr>)}</tbody></table></TableFrame><p>Offset {historyOffset}; up to 25 revisions. Exact recorded actor and action, no inferred effectiveness.</p><Button disabled={historyBusy||historyOffset===0} onClick={()=>readHistory(Math.max(0,historyOffset-25))}>Previous revisions</Button><Button disabled={historyBusy||history.length<25||historyOffset>=10000} onClick={()=>readHistory(historyOffset+25)}>Next revisions</Button></>}</SectionCard></>}</>;
}
