'use client';
import {useState} from 'react';
import type {QaSession,Recommendation} from '../lib/product-records';
import {useQaCommand} from './useQaCommand';
import {Button,Feedback,InputControl} from './ui';
export default function RecommendationActions({row,session,onChanged}:{row:Recommendation;session:QaSession;onChanged:()=>void}){
 const [reason,setReason]=useState(''),[rationale,setRationale]=useState(row.rationale),[action,setAction]=useState(row.proposed_action),[owner,setOwner]=useState(row.responsible_person_ref??''),[team,setTeam]=useState(row.responsible_team_ref??''),[date,setDate]=useState(row.target_date??'');
 const cmd=useQaCommand(session,onChanged),author=session.subject===row.created_by&&session.roles.includes('AUTHOR'),reviewer=session.roles.includes('REVIEWER');
 async function mutation(endpoint:string,payload:Record<string,unknown>={}){const result=await cmd.run(`recommendations/${encodeURIComponent(row.record_id)}/${endpoint}`,'POST',{expected_revision:row.revision,...payload});if(result)onChanged();}
 async function update(){const result=await cmd.run('recommendations/'+encodeURIComponent(row.record_id),'PUT',{expected_revision:row.revision,draft:{canonical_asset_id:row.canonical_asset_id,case_ref:row.case_ref,rationale,proposed_action:action,priority:row.priority,responsible_person_ref:owner||null,responsible_team_ref:team||null,target_date:date||null,existing_work_order_ref:row.existing_work_order_ref,evidence_selections:row.supporting_evidence.map(e=>({kind:e.kind,record_id:e.record_id,mode:e.mode}))}});if(result)onChanged();}
 const next:Record<string,string>={PROPOSED:'PLANNED',PLANNED:'IN_PROGRESS',IN_PROGRESS:'COMPLETED'};
 return <div className="engineering-form"><h3>Authorized NADI local workflow</h3>{cmd.error&&<Feedback error>{cmd.error}</Feedback>}{author&&row.status==='DRAFT'&&<><div className="filter-grid"><InputControl id="recommendation-rationale" label="Recommendation rationale" value={rationale} maxLength={6000} onChange={e=>setRationale(e.target.value)}/><InputControl id="recommendation-action" label="Proposed local action" value={action} maxLength={6000} onChange={e=>setAction(e.target.value)}/><InputControl id="recommendation-owner" label="Responsible person reference (optional)" value={owner} maxLength={160} onChange={e=>setOwner(e.target.value)}/><InputControl id="recommendation-team" label="Responsible team reference (optional)" value={team} maxLength={160} onChange={e=>setTeam(e.target.value)}/><InputControl id="recommendation-date" type="date" label="Local target date (optional)" value={date} onChange={e=>setDate(e.target.value)}/></div><Button disabled={cmd.busy||!rationale.trim()||!action.trim()} onClick={update}>Save recommendation draft</Button><Button disabled={cmd.busy} onClick={()=>mutation('submit')}>Submit recommendation for review</Button></>}
 <InputControl id="recommendation-reason" label="Recommendation review / follow-up rationale" value={reason} maxLength={6000} onChange={e=>setReason(e.target.value)}/><div className="engineering-actions">{reviewer&&row.status==='IN_REVIEW'&&['APPROVED','REJECTED'].map(decision=><Button key={decision} disabled={cmd.busy||!reason.trim()} onClick={()=>mutation('review',{decision,reason})}>{decision==='APPROVED'?'Approve recommendation':'Reject recommendation'}</Button>)}{author&&row.status==='REJECTED'&&<Button disabled={cmd.busy||!reason.trim()} onClick={()=>mutation('revise',{reason})}>Revise recommendation</Button>}{author&&row.status==='APPROVED'&&next[row.follow_up_status]&&<><Button disabled={cmd.busy||!reason.trim()} onClick={()=>mutation('followup',{status:next[row.follow_up_status],reason})}>Record local {next[row.follow_up_status]}</Button><Button disabled={cmd.busy||!reason.trim()} onClick={()=>mutation('followup',{status:'CANCELLED',reason})}>Cancel local follow-up</Button></>}{reviewer&&row.status==='APPROVED'&&row.follow_up_status==='COMPLETED'&&<Button disabled={cmd.busy||!reason.trim()||!row.supporting_evidence.length} onClick={()=>mutation('verify_completion',{reason,evidence_selections:row.supporting_evidence.map(e=>({kind:e.kind,record_id:e.record_id,mode:'FROZEN_SNAPSHOT'}))})}>Independently verify local completion evidence</Button>}</div><p className="section-note">Server checks identity, independent review, asset scope, exact revision and evidence. Existing WO remains read-only. Local completion does not certify physical maintenance or plant effectiveness.</p>
 </div>;
}
