"use client";
import RecommendationActions from "./RecommendationActions";
import Link from "next/link";
import type {Recommendation,QaSession} from "../lib/product-records";
import {qaRecordLink} from "../lib/product-records";
import {SectionCard,StatusBadge,TableFrame} from "./ui";
export default function RecommendationDetail({row,session,onChanged}:{row:Recommendation;session?:QaSession;onChanged?:()=>void}){
 return <SectionCard className="product-record-detail"><div className="section-heading"><h2>Recommendation {row.record_id}</h2><StatusBadge value={row.status} mode="raw-neutral"/></div><p className="section-note">SYNTHETIC QA · NADI-owned · {row.canonical_asset_id} · Revision {row.revision} · {row.provenance}</p>
  <div className="product-context-grid"><div><h3>Proposed action</h3><p>{row.proposed_action}</p><h3>Engineering rationale</h3><p>{row.rationale}</p></div><div><h3>Responsibility / follow-up</h3><dl className="asset-facts"><div><dt>Responsible person reference</dt><dd>{row.responsible_person_ref??"NOT ASSIGNED"}</dd></div><div><dt>Responsible team reference</dt><dd>{row.responsible_team_ref??"NOT ASSIGNED"}</dd></div><div><dt>Local target date</dt><dd>{row.target_date??"UNKNOWN"}</dd></div><div><dt>Local follow-up</dt><dd>{row.follow_up_status}</dd></div><div><dt>Existing WO reference</dt><dd>{row.existing_work_order_ref??"NOT LINKED"}</dd></div></dl></div></div>
  <div className="product-context-grid"><div><h3>Independent record review</h3>{row.review?<p>{row.review.decision} · {row.review.reviewer} · {row.review.decided_at}<br/>{row.review.rationale}</p>:<p>Review decision NOT AVAILABLE.</p>}<p>Case reference: <Link href={qaRecordLink("cases",row.case_ref)}>{row.case_ref}</Link></p>{row.reviewed_case&&<p>Reviewed case revision {row.reviewed_case.revision} · {row.reviewed_case.reviewed_at}<small className="table-subtext">Stable version: {row.reviewed_case.stable_version}</small></p>}</div><div><h3>Completion verification</h3>{row.completion_verification?<p>{row.completion_verification.reviewer} · {row.completion_verification.verified_at}<br/>{row.completion_verification.reason}<small className="table-subtext">{row.completion_verification.scope}</small></p>:<p>NOT VERIFIED — local completion is not independently verified effectiveness.</p>}</div></div>
  <h3>Evidence provenance</h3>{row.supporting_evidence.length?<TableFrame minWidth={650} label="Version-bound recommendation evidence"><table><thead><tr><th>Kind / record</th><th>Reference mode</th><th>Exact version / source time</th></tr></thead><tbody>{row.supporting_evidence.map((e,i)=><tr key={i}><td>{e.kind}<small className="table-subtext">{e.record_id}</small></td><td>{e.mode}</td><td>{e.stable_version}<small className="table-subtext">{e.source_timestamp??"UNKNOWN"}</small></td></tr>)}</tbody></table></TableFrame>:<p>No supporting evidence returned; no evidence is fabricated.</p>}
  {session&&onChanged&&<RecommendationActions key={row.record_id+":"+row.revision} row={row} session={session} onChanged={onChanged}/>}
  <p className="section-note">Human priority is not risk. No WO create, approve, update, assign or close capability. Independent reviewer and expected revision checks remain server-enforced in the existing workflow.</p><Link className="button secondary" href={qaRecordLink("recommendations",row.record_id)}>Authorized local workflow →</Link>
 </SectionCard>;
}
