"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import type {Recommendation} from "../lib/product-records";
import {pageCounts,recordMatches,validRecordId,qaRecordLink} from "../lib/product-records";
import {useQaRecords} from "./useQaRecords";
import QaProductBoundary from "./QaProductBoundary";
import QaRecordReader from "./QaRecordReader";
import RecommendationDetail from "./RecommendationDetail";
import {Button,EmptyState,InputControl,PageHeader,Pagination,SectionCard,StatCard,StatusBadge,TableFrame} from "./ui";
const reviewStates=["DRAFT","IN_REVIEW","APPROVED","REJECTED"];
const followStates=["PROPOSED","PLANNED","IN_PROGRESS","COMPLETED","CANCELLED","VERIFIED"];
export default function RecommendationWorkspace({qaEnabled,board=false}:{qaEnabled:boolean;board?:boolean}){
 const [offset,setOffset]=useState(0),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[asset,setAsset]=useState(""),[follow,setFollow]=useState(""),[selected,setSelected]=useState<string|null>(null);
 const {state,page,session,reload}=useQaRecords<Recommendation>("recommendations",qaEnabled,offset);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("record");setSelected(validRecordId(id)?id:null);},[]);
 const invalidate=useCallback(()=>reload(),[reload]);
 const rows=page?.items.filter(row=>recordMatches(row,asset,status,search,[row.record_id,row.canonical_asset_id,row.case_ref,row.rationale,row.proposed_action,row.responsible_person_ref??""].join(" "))&&(!follow||row.follow_up_status===follow))??[];
 const counts=pageCounts(rows), reviewQueue=rows.filter(row=>row.status==="IN_REVIEW"), followQueue=rows.filter(row=>row.status==="APPROVED");
 const base=board?"/action-board":"/recommendations";
 function selectRecord(id:string|null){setSelected(id);window.history.replaceState({},"",`${base}${id?"?record="+encodeURIComponent(id):""}`);}
 function register(items:Recommendation[],label:string){
  if(!items.length)return <EmptyState title="No authorized recommendations match this page context." detail="Empty records are not proof of no operational actions or findings."/>;
  if(board)return <TableFrame minWidth={600} label={label}><table><thead><tr><th>Recommendation / QA asset</th><th>Local status</th><th>Responsible reference / target date</th><th>Open context</th></tr></thead><tbody>{items.map(row=><tr key={row.record_id}><td><a className="asset-row-link" href={`${base}?record=${encodeURIComponent(row.record_id)}`} onClick={e=>{e.preventDefault();selectRecord(row.record_id);}}>{row.record_id}</a><small className="table-subtext">{row.canonical_asset_id} · Revision {row.revision}</small></td><td><StatusBadge value={row.status} mode="raw-neutral"/><small className="table-subtext">Follow-up: {row.follow_up_status}<br/>{row.completion_verification?"Independent verification recorded":"NOT VERIFIED"}</small></td><td>{row.responsible_person_ref??row.responsible_team_ref??"NOT ASSIGNED"}<small className="table-subtext">{row.target_date??"Date UNKNOWN"}</small></td><td><Link href={qaRecordLink("cases",row.case_ref)}>Exact case →</Link></td></tr>)}</tbody></table></TableFrame>;
  return items.length?<TableFrame minWidth={1050} label={label}><table><thead><tr><th>NADI recommendation / case</th><th>QA asset</th><th>Proposed action / rationale</th><th>Record review</th><th>Local follow-up</th><th>Responsible reference / target date</th><th>Existing WO</th></tr></thead><tbody>{items.map(row=><tr key={row.record_id}><td><a className="asset-row-link" href={`${base}?record=${encodeURIComponent(row.record_id)}`} onClick={e=>{e.preventDefault();selectRecord(row.record_id);}}>{row.record_id}</a><small className="table-subtext">Revision {row.revision} · <Link href={qaRecordLink("cases",row.case_ref)}>{row.case_ref}</Link></small></td><td>{row.canonical_asset_id}</td><td className="wide-cell">{row.proposed_action}<small className="table-subtext">{row.rationale}</small></td><td><StatusBadge value={row.status} mode="raw-neutral"/></td><td><StatusBadge value={row.follow_up_status} mode="raw-neutral"/><small className="table-subtext">{row.completion_verification?"Independent verification recorded":"Effectiveness NOT VERIFIED"}</small></td><td>{row.responsible_person_ref??row.responsible_team_ref??"NOT ASSIGNED"}<small className="table-subtext">{row.target_date??"Date UNKNOWN"}</small></td><td>{row.existing_work_order_ref??"NOT LINKED"}<small className="table-subtext">Informational only</small></td></tr>)}</tbody></table></TableFrame>:<EmptyState title="No authorized recommendations match this page context." detail="Empty records are not proof of no operational actions or findings."/>;
 }
 return <div className="product-workspace"><PageHeader eyebrow="NADI-owned decision records" title={board?"Action Board":"Recommendations"} description={board?"Independent review and local follow-up attention. Counts reconcile with the filtered authorized page; no risk ranking or Maximo execution authority.":"Traceable proposals, reviewed cases, responsibility and local follow-up. NADI recommendation review does not approve a Maximo Work Order."} actions={<Link className="button secondary" href={board?"/recommendations":"/action-board"}>{board?"Recommendation register":"Action Board"} →</Link>}/>
  <QaProductBoundary state={state} reload={reload}/>
  <section className="stat-grid product-stat-grid">
   {board?<><StatCard label="Awaiting local review" value={page?reviewQueue.length:"UNKNOWN"} detail="Filtered page · IN_REVIEW recommendations"/><StatCard label="Approved local follow-up" value={page?followQueue.length:"UNKNOWN"} detail="Filtered page · APPROVED records"/><StatCard label="Completion awaiting verification" value={page?followQueue.filter(row=>row.follow_up_status==="COMPLETED"&&!row.completion_verification).length:"UNKNOWN"} detail="Local completion does not prove effectiveness"/><StatCard label="Missing owner or date" value={page?rows.filter(row=>(!row.responsible_person_ref&&!row.responsible_team_ref)||!row.target_date).length:"UNKNOWN"} detail="Filtered page · unknown context; not urgency"/></>:<><StatCard label="Authorized recommendations" value={page?page.total:"UNKNOWN"} detail="Synthetic QA server-visible population"/><StatCard label="Matching page records" value={page?rows.length:"UNKNOWN"} detail="Search/filter covers this page only"/><StatCard label="Awaiting local review" value={page?(counts.IN_REVIEW??0):"UNKNOWN"} detail="Filtered page · no inferred operational approval"/><StatCard label="Approved records" value={page?(counts.APPROVED??0):"UNKNOWN"} detail="Record review only; not healthy or effective"/></>}
  </section>
  {state==="ready"&&page&&session&&<><SectionCard className="filter-card"><div className="filter-grid"><InputControl id="recommendation-page-search" label="Search this recommendation page" value={search} onChange={e=>setSearch(e.target.value)}/><label>Local review status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All record states</option>{reviewStates.map(x=><option key={x}>{x}</option>)}</select></label><label>Local follow-up status<select value={follow} onChange={e=>setFollow(e.target.value)}><option value="">All follow-up states</option>{followStates.map(x=><option key={x}>{x}</option>)}</select></label><label>QA asset on this page<select value={asset} onChange={e=>setAsset(e.target.value)}><option value="">All page assets</option>{[...new Set(page.items.map(row=>row.canonical_asset_id))].map(id=><option key={id}>{id}</option>)}</select></label><Button onClick={()=>{setSearch("");setStatus("");setFollow("");setAsset("");}}>Clear page filters</Button></div><p className="section-note">Only the current 25 server-authorized records are searched or counted by status. Pagination remains server-side. Dates are original local target dates, not inferred deadlines or urgency.</p></SectionCard>
   {board?<div className="product-context-grid"><SectionCard><h2>Independent recommendation review queue</h2>{register(reviewQueue,"Independent recommendation review queue")}</SectionCard><SectionCard><h2>Local follow-up / completion verification</h2>{register(followQueue,"Approved local follow-up register")}</SectionCard></div>:<SectionCard><div className="section-heading"><h2>Recommendation register</h2><span className="dataset-badge compact">SYNTHETIC QA · NADI-owned</span></div>{register(rows,"NADI recommendation register")}</SectionCard>}
   <SectionCard><Pagination meta={page} onChange={next=>{setOffset(next);setSelected(null);setAsset("");}}/></SectionCard>
   {selected&&<><Button onClick={()=>selectRecord(null)}>Close recommendation detail</Button><QaRecordReader<Recommendation> key={`${session.subject}:${selected}`} resource="recommendations" id={selected} render={row=><RecommendationDetail row={row}/>} onInvalid={invalidate}/></>}
  </>}
 </div>;
}
